# ASSOCIATION RULES
Express how product/services relate to each other, and tend to group together.

Library import

In [24]:
#vanno importate pandas e numpy e matplot per fare i grafici
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split  
from pandas import DataFrame

In [25]:
df = pd.read_csv(r'C:\Users\jigok\OneDrive\Desktop\UniPISA\1semestre1Anno\Data Mining\Progetto\Dataset AR\All_values_Train_HR_Employee_Attrition_No_OverallSatisfaction.csv')

In [26]:
df.head(5) #fammi vedere le prime 10 righe

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,...,OverTime,PercentSalaryHike,RelationshipSatisfaction,StockOptionLevel,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,MonthlyHours,TaxRate
0,52.0,No,Travel_Rarely,9,4,2,Male,3,3,Research Director,...,No,17,3,0,2.0,2,8.0,7,156.613636,0.387172
1,36.0,No,Travel_Rarely,1,1,2,Male,3,5,Manager,...,Yes,14,3,1,3.0,3,1.0,8,157.942308,0.411421
2,25.0,No,Travel_Frequently,16,3,3,Male,3,2,Sales Executive,...,Yes,25,3,1,4.0,3,1.0,5,448.055556,0.704402
3,33.0,No,Travel_Rarely,5,4,2,Male,3,1,Research Scientist,...,No,14,2,0,1.0,3,3.0,7,271.907692,0.841632
4,31.0,No,Travel_Rarely,9,2,3,Female,3,1,Laboratory Technician,...,No,12,3,0,2.0,3,10.0,2,106.373333,0.207947

In [27]:
df.describe()

,Age,DistanceFromHome,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,RelationshipSatisfaction,StockOptionLevel,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,MonthlyHours,TaxRate
count,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000
mean,36.554926,9.201586,2.886750,2.684032,2.750849,1.919592,2.703284,6932.335221,2.836920,15.207248,2.716874,0.793884,2.665912,2.767837,6.326161,3.919592,234.245826,0.463811
std,8.266129,8.241818,1.008285,1.092567,0.729354,1.007506,1.087061,5453.370217,2.484993,3.589332,1.078137,0.865362,1.187828,0.721713,4.523567,3.435392,130.196628,0.320030
min,18.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1009.000000,0.000000,11.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,26.043478,0.000000
25%,30.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,3072.000000,1.000000,12.000000,2.000000,0.000000,2.000000,2.000000,3.000000,2.000000,130.630208,0.129730
50%,35.000000,7.000000,3.000000,3.000000,3.000000,2.000000,3.000000,5079.000000,2.000000,14.000000,3.000000,1.000000,2.000000,3.000000,5.000000,3.000000,212.279070,0.528359
75%,42.000000,14.000000,4.000000,4.000000,3.000000,2.000000,4.000000,8840.500000,4.000000,18.000000,4.000000,1.000000,3.000000,3.000000,9.000000,7.000000,309.906250,0.762560
max,60.000000,29.000000,5.000000,4.000000,4.000000,5.000000,4.000000,26997.000000,9.000000,25.000000,4.000000,3.000000,6.000000,4.000000,20.000000,16.000000,590.976744,0.951396

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       883 non-null    float64
 1   Attrition                 883 non-null    object
 2   BusinessTravel            883 non-null    object
 3   DistanceFromHome          883 non-null    int64
 4   Education                 883 non-null    int64
 5   EnvironmentSatisfaction   883 non-null    int64
 6   Gender                    883 non-null    object
 7   JobInvolvement            883 non-null    int64
 8   JobLevel                  883 non-null    int64
 9   JobRole                   883 non-null    object
 10  JobSatisfaction           883 non-null    int64
 11  MonthlyIncome             883 non-null    float64
 12  NumCompaniesWorked        883 non-null    int64
 13  OverTime                  883 non-null    object
 14  PercentSalaryHike         883 non-null    int64
 15  RelationshipSatisfaction  883 non-null    int64
 16  StockOptionLevel          883 non-null    int64
 17  TrainingTimesLastYear     883 non-null    float64
 18  WorkLifeBalance           883 non-null    int64
 19  YearsAtCompany            883 non-null    float64
 20  YearsInCurrentRole        883 non-null    int64
 21  MonthlyHours              883 non-null    float64
 22  TaxRate                   883 non-null    float64
dtypes: float64(6), int64(12), object(5)
memory usage: 158.8+ KB

In [29]:
#numero bin con la distribuzione istogrammi variabili
#Apply binning to continuous features

df['AgeBin'] = pd.cut(df['Age'].astype(int), 6, right=False)
df['DistanceFromHomeBin'] = pd.cut(df['DistanceFromHome'].astype(int), 10, right=False)
df['PercentSalaryHikeBin'] = pd.cut(df['PercentSalaryHike'].astype(int), 5, right=False)
df['MonthlyIncomeBin'] = pd.cut(df['MonthlyIncome'].astype(int), 10, right=False)
df['MonthlyHoursBin'] = pd.cut(df['MonthlyHours'].astype(int), 10, right=False)



df.drop(['Age', 'MonthlyIncome', 'MonthlyHours','DistanceFromHome','PercentSalaryHike'], axis=1, inplace=True)

df.head()

,Attrition,BusinessTravel,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,NumCompaniesWorked,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,TaxRate,AgeBin,DistanceFromHomeBin,PercentSalaryHikeBin,MonthlyIncomeBin,MonthlyHoursBin
0,No,Travel_Rarely,4,2,Male,3,3,Research Director,3,9,...,2.0,2,8.0,7,0.387172,"[46.0, 53.0)","[6.6, 9.4)","[16.6, 19.4)","[6206.6, 8805.4)","[138.8, 195.2)"
1,No,Travel_Rarely,1,2,Male,3,5,Manager,3,1,...,3.0,3,1.0,8,0.411421,"[32.0, 39.0)","[1.0, 3.8)","[13.8, 16.6)","[3607.8, 6206.6)","[138.8, 195.2)"
2,No,Travel_Frequently,3,3,Male,3,2,Sales Executive,4,1,...,4.0,3,1.0,5,0.704402,"[25.0, 32.0)","[15.0, 17.8)","[22.2, 25.014)","[3607.8, 6206.6)","[420.8, 477.2)"
3,No,Travel_Rarely,4,2,Male,3,1,Research Scientist,2,2,...,1.0,3,3.0,7,0.841632,"[32.0, 39.0)","[3.8, 6.6)","[13.8, 16.6)","[1009.0, 3607.8)","[251.6, 308.0)"
4,No,Travel_Rarely,2,3,Female,3,1,Laboratory Technician,4,1,...,2.0,3,10.0,2,0.207947,"[25.0, 32.0)","[6.6, 9.4)","[11.0, 13.8)","[6206.6, 8805.4)","[82.4, 138.8)"

Mapping

In [30]:
df['Education'] = df['Education'].map(
    {1: 'Below College', 2: 'College', 3:'Bachelor', 4:'Master', 5:'Doctor'}).astype(str)

df['JobLevel'] = df['JobLevel'].map(
    {1: 'EntryLevel', 2: 'MidLevel', 3:'SeniorLevel', 4:'Manager', 5:'Director'}).astype(str)


df['AgeBin'] = df['AgeBin'].astype(str) + '_Age'
df['MonthlyIncomeBin'] = df['MonthlyIncomeBin'].astype(str) + '_Income'
df['MonthlyHoursBin'] = df['MonthlyHoursBin'].astype(str) + '_Hours'
df['DistanceFromHomeBin'] = df['DistanceFromHomeBin'].astype(str) + '_Distance'
df['YearsAtCompany'] = df['YearsAtCompany'].astype(str) + '_YearsAtCompany'
df['PercentSalaryHikeBin'] = df['PercentSalaryHikeBin'].astype(str) + '_%'

df['NumCompaniesWorked'] = df['NumCompaniesWorked'].astype(str) + '_companies'
df['StockOptionLevel'] = df['StockOptionLevel'].astype(str) + '_stockOption'
df['TrainingTimesLastYear'] = df['TrainingTimesLastYear'].astype(str) + '_Time'
df['YearsInCurrentRole'] = df['YearsInCurrentRole'].astype(str) + '_YearsInCurrentRole'
df['TaxRate'] = df['TaxRate'].astype(str) + '_TaxRate'

df['EnvironmentSatisfaction'] = df['EnvironmentSatisfaction'].astype(str) + '_ESat'
df['JobSatisfaction'] = df['JobSatisfaction'].astype(str) + '_JSat'
df['JobInvolvement'] = df['JobInvolvement'].astype(str) + '_JIvol'
df['WorkLifeBalance'] = df['WorkLifeBalance'].astype(str) + '_WLBalance'
df['RelationshipSatisfaction'] = df['RelationshipSatisfaction'].astype(str) + '_RSat'


df.head(10)

,Attrition,BusinessTravel,Education,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,NumCompaniesWorked,...,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,TaxRate,AgeBin,DistanceFromHomeBin,PercentSalaryHikeBin,MonthlyIncomeBin,MonthlyHoursBin
0,No,Travel_Rarely,Master,2_ESat,Male,3_JIvol,SeniorLevel,Research Director,3_JSat,9_companies,...,2.0_Time,2_WLBalance,8.0_YearsAtCompany,7_YearsInCurrentRole,0.3871716731969235_TaxRate,"[46.0, 53.0)_Age","[6.6, 9.4)_Distance","[16.6, 19.4)_%","[6206.6, 8805.4)_Income","[138.8, 195.2)_Hours"
1,No,Travel_Rarely,Below College,2_ESat,Male,3_JIvol,Director,Manager,3_JSat,1_companies,...,3.0_Time,3_WLBalance,1.0_YearsAtCompany,8_YearsInCurrentRole,0.4114209180567393_TaxRate,"[32.0, 39.0)_Age","[1.0, 3.8)_Distance","[13.8, 16.6)_%","[3607.8, 6206.6)_Income","[138.8, 195.2)_Hours"
2,No,Travel_Frequently,Bachelor,3_ESat,Male,3_JIvol,MidLevel,Sales Executive,4_JSat,1_companies,...,4.0_Time,3_WLBalance,1.0_YearsAtCompany,5_YearsInCurrentRole,0.7044017358958462_TaxRate,"[25.0, 32.0)_Age","[15.0, 17.8)_Distance","[22.2, 25.014)_%","[3607.8, 6206.6)_Income","[420.8, 477.2)_Hours"
3,No,Travel_Rarely,Master,2_ESat,Male,3_JIvol,EntryLevel,Research Scientist,2_JSat,2_companies,...,1.0_Time,3_WLBalance,3.0_YearsAtCompany,7_YearsInCurrentRole,0.8416317754894195_TaxRate,"[32.0, 39.0)_Age","[3.8, 6.6)_Distance","[13.8, 16.6)_%","[1009.0, 3607.8)_Income","[251.6, 308.0)_Hours"
4,No,Travel_Rarely,College,3_ESat,Female,3_JIvol,EntryLevel,Laboratory Technician,4_JSat,1_companies,...,2.0_Time,3_WLBalance,10.0_YearsAtCompany,2_YearsInCurrentRole,0.20794685384808226_TaxRate,"[25.0, 32.0)_Age","[6.6, 9.4)_Distance","[11.0, 13.8)_%","[6206.6, 8805.4)_Income","[82.4, 138.8)_Hours"
5,No,Travel_Rarely,Bachelor,4_ESat,Male,4_JIvol,EntryLevel,Research Scientist,3_JSat,1_companies,...,2.0_Time,3_WLBalance,1.0_YearsAtCompany,2_YearsInCurrentRole,0.8559182118364237_TaxRate,"[32.0, 39.0)_Age","[6.6, 9.4)_Distance","[11.0, 13.8)_%","[1009.0, 3607.8)_Income","[251.6, 308.0)_Hours"
6,No,Travel_Rarely,College,3_ESat,Male,3_JIvol,EntryLevel,Sales Representative,2_JSat,2_companies,...,0.0_Time,3_WLBalance,9.0_YearsAtCompany,3_YearsInCurrentRole,0.5842782277274893_TaxRate,"[25.0, 32.0)_Age","[3.8, 6.6)_Distance","[11.0, 13.8)_%","[6206.6, 8805.4)_Income","[364.4, 420.8)_Hours"
7,No,Travel_Frequently,Below College,4_ESat,Male,4_JIvol,MidLevel,Sales Executive,4_JSat,1_companies,...,2.0_Time,3_WLBalance,1.0_YearsAtCompany,5_YearsInCurrentRole,0.892640796497331_TaxRate,"[18.0, 25.0)_Age","[1.0, 3.8)_Distance","[19.4, 22.2)_%","[1009.0, 3607.8)_Income","[195.2, 251.6)_Hours"
8,No,Travel_Rarely,College,4_ESat,Male,4_JIvol,MidLevel,Research Scientist,1_JSat,3_companies,...,2.0_Time,3_WLBalance,3.0_YearsAtCompany,2_YearsInCurrentRole,0.8533628779979145_TaxRate,"[39.0, 46.0)_Age","[15.0, 17.8)_Distance","[11.0, 13.8)_%","[1009.0, 3607.8)_Income","[251.6, 308.0)_Hours"
9,No,Travel_Rarely,Bachelor,2_ESat,Male,3_JIvol,MidLevel,Manufacturing Director,2_JSat,1_companies,...,5.0_Time,2_WLBalance,1.0_YearsAtCompany,8_YearsInCurrentRole,0.7721497543621887_TaxRate,"[32.0, 39.0)_Age","[26.2, 29.028)_Distance","[11.0, 13.8)_%","[1009.0, 3607.8)_Income","[82.4, 138.8)_Hours"

Conto le transazioni che contengono attrition(yes)e le totali

In [31]:
df['Attrition'].value_counts()

No     730
Yes    153
Name: Attrition, dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attrition                 883 non-null    object
 1   BusinessTravel            883 non-null    object
 2   Education                 883 non-null    object
 3   EnvironmentSatisfaction   883 non-null    object
 4   Gender                    883 non-null    object
 5   JobInvolvement            883 non-null    object
 6   JobLevel                  883 non-null    object
 7   JobRole                   883 non-null    object
 8   JobSatisfaction           883 non-null    object
 9   NumCompaniesWorked        883 non-null    object
 10  OverTime                  883 non-null    object
 11  RelationshipSatisfaction  883 non-null    object
 12  StockOptionLevel          883 non-null    object
 13  TrainingTimesLastYear     883 non-null    object
 14  WorkLifeBalance           883 non-null    object
 15  YearsAtCompany            883 non-null    object
 16  YearsInCurrentRole        883 non-null    object
 17  TaxRate                   883 non-null    object
 18  AgeBin                    883 non-null    object
 19  DistanceFromHomeBin       883 non-null    object
 20  PercentSalaryHikeBin      883 non-null    object
 21  MonthlyIncomeBin          883 non-null    object
 22  MonthlyHoursBin           883 non-null    object
dtypes: object(23)
memory usage: 158.8+ KB

Ora so che il support di ATTRITION Ã¨ dato da 153/883 ed Ã¨ 0.17 quindi 17

# Creo i baskets

In [33]:
baskets = df.values.tolist()

In [34]:
baskets[0]

['No',
 'Travel_Rarely',
 'Master',
 '2_ESat',
 'Male',
 '3_JIvol',
 'SeniorLevel',
 'Research Director',
 '3_JSat',
 '9_companies',
 'No',
 '3_RSat',
 '0_stockOption',
 '2.0_Time',
 '2_WLBalance',
 '8.0_YearsAtCompany',
 '7_YearsInCurrentRole',
 '0.3871716731969235_TaxRate',
 '[46.0, 53.0)_Age',
 '[6.6, 9.4)_Distance',
 '[16.6, 19.4)_%',
 '[6206.6, 8805.4)_Income',
 '[138.8, 195.2)_Hours']

# Apriori Algorithm

In [35]:
from fim import apriori

In [36]:
help(apriori)

Help on built-in function apriori in module fim:

apriori(...)
    apriori (tracts, target='s', supp=10, zmin=1, zmax=None, report='a',
             eval='x', agg='x', thresh=10, prune=None, algo='b', mode='',
             border=None)
    Find frequent item sets with the Apriori algorithm.
    tracts  transaction database to mine (mandatory)
            The database must be an iterable of transactions;
            each transaction must be an iterable of items;
            each item must be a hashable object.
            If the database is a dictionary, the transactions are
            the keys, the values their (integer) multiplicities.
    target  type of frequent item sets to find     (default: s)
            s/a   sets/all   all     frequent item sets
            c     closed     closed  frequent item sets
            m     maximal    maximal frequent item sets
            g     gens       generators
            r     rules      association rules
    supp    minimum support of an item set         (default: 10)
            (positive: percentage, negative: absolute number)
    conf    minimum confidence of an assoc. rule   (default: 80%)
    zmin    minimum number of items per item set   (default: 1)
    zmax    maximum number of items per item set   (default: no limit)
    report  values to report with an item set      (default: a)
            a     absolute item set support (number of transactions)
            s     relative item set support as a fraction
            S     relative item set support as a percentage
            e     value of item set evaluation measure
            E     value of item set evaluation measure as a percentage
            (     combine values in a tuple (must be first character)
            [     combine values in a list  (must be first character)
            #     pattern spectrum as a dictionary  (no patterns)
            =     pattern spectrum as a list        (no patterns)
            |     pattern spectrum as three columns (no patterns)
            for target 'r' (association rules) also available:
            b     absolute body set  support (number of transactions)
            x     relative body set  support as a fraction
            X     relative body set  support as a percentage
            h     absolute head item support (number of transactions)
            y     relative head item support as a fraction
            Y     relative head item support as a percentage
            c     rule confidence as a fraction
            C     rule confidence as a percentage
            l     lift value of a rule (confidence/prior)
            L     lift value of a rule as a percentage
            Q     support of the empty set (total number of transactions)
    eval    measure for item set evaluation        (default: x)
            x     none       no measure / zero (default)
            b     ldratio    binary logarithm of support quotient       (+)
            c     conf       rule confidence                            (+)
            d     confdiff   absolute confidence difference to prior    (+)
            l     lift       lift value (confidence divided by prior)   (+)
            a     liftdiff   absolute difference of lift value to 1     (+)
            q     liftquot   difference of lift quotient to 1           (+)
            v     cvct       conviction (inverse lift negated head)     (+)
            e     cvctdiff   absolute difference of conviction to 1     (+)
            r     cvctquot   difference of conviction quotient to 1     (+)
            k     cprob      conditional probability ratio              (+)
            j     import     importance (binary log. of prob. ratio)    (+)
            z     cert       certainty factor (relative conf. change)   (+)
            n     chi2       normalized chi^2 measure                   (+)
            p     chi2pval   p-value f/ (unnormalized) chi^2 measure    (-)
            y     yates      normalized chi^2 with Yates' correction    (+)
            t     yatespval  p-value f/ Yates-corrected chi^2 measure   (-)
            i     info       information difference to prior            (+)
            g     infopval   p-value f/ G statistic/info. difference    (-)
            f     fetprob    Fisher's exact test (table probability)    (-)
            h     fetchi2    Fisher's exact test (chi^2 measure)        (-)
            m     fetinfo    Fisher's exact test (mutual information)   (-)
            s     fetsupp    Fisher's exact test (support)              (-)
            Measures marked with (+) must meet or exceed the threshold,
            measures marked with (-) must not exceed the threshold
            in order for the item set to be reported.
    agg     evaluation measure aggregation mode    (default: x)
            x     none       no aggregation (use first value)
            m     min        minimum of individual measure values
            n     max        maximum of individual measure values
            a     avg        average of individual measure values
    thresh  threshold for evaluation measure       (default: 10%)
    prune   min. size for evaluation filtering     (default: no pruning)
            = 0   backward filtering       (no subset check)
            < 0   weak   forward filtering (one subset  must qualify)
            > 0   strong forward filtering (all subsets must qualify)
    algo    algorithm variant to use               (default: a)
            b     basic      standard algorithm (only choice)
    mode    operation mode indicators/flags        (default: None)
            x     do not use perfect extension pruning
            t/T   do not organize transactions as a prefix tree
            y     a-posteriori pruning of infrequent item sets
            z     invalidate evaluation below expected support
            o     use original rule support definition (body & head)
    border  support border for filtering item sets (default: None)
            Must be a list or tuple of (absolute) minimum support values
            per item set size (by which the list/tuple is indexed).
    appear  dictionary mapping items to item appearance indicators,
            with the key None referring to the default item appearance.
            (If None does not occur as a key or no dictionary is given,
            the default item appearance indicator is 'both'.)
            This parameter is only used if the target type is rules.
            * item may not appear anywhere in a rule:
              '-', 'n', 'none', 'neither', 'ignore'
            * item may appear only in rule body/antecedent:
              'i', 'in', 'inp', 'input', 'b', 'body',
              'a', 'ante', 'antecedent'
            * item may appear only in rule head/consequent:
              'o', 'out',      'output', 'h', 'head',
              'c', 'cons', 'consequent'
            * item may appear anywhere in a rule:
              'io', 'i&o', 'inout', 'in&out', 'bh', 'b&h', 'both'
    returns if report is not in ['#','=','|']:
              if the target is association rules:
                a list of rules (i.e. tuples with two or more elements),
                each consisting of a head/consequent item, a tuple with
                a body/antecedent item set, and the values selected by
                the parameter 'report', which may be combined into a
                tuple or a list if report[0] is '(' or '[', respectively.
              if the target is a type of item sets:
                a list of patterns (i.e. tuples with one or more elements),
                each consisting of a tuple with a found frequent item set
                and the values selected by the parameter 'report', which
                may be combined into a tuple or list if report[0] is '('
                or '[', respectively
            if report in ['#','=','|']:
              a pattern spectrum as a dictionary mapping pattern sizes
              to the corresponding occurrence support ranges, as a list
              of triplets (size, min. support, max. support) or as three
              columns for sizes and minimum and maximum support values

# Description of the Value

We have ecide to do some proves with different characterized value of support. This value are 2,10,20,30,40,50,60,70,80,90.
After that we have to do some proves with different type of target , a for frequent itemset, m for maximal itemset e c for closed itemset. 

For choosing the best combination we try to create the frequent itemset with 2/3/4 min value.

# Support = 25%

 Frequent Itemsets with min value 2/3/4

In [37]:
itemsets = apriori(baskets, supp=25, report ='s', target='a',zmin = 2)
print('Number of itemsets:', len(itemsets))
itemsets

Number of itemsets: 72

[(('3.0_Time', 'No'), 0.2582106455266138),
 (('4_ESat', 'No'), 0.26160815402038506),
 (('4_JSat', 'No'), 0.27519818799546997),
 (('4_RSat', 'No'), 0.26840317100792754),
 (('[3607.8, 6206.6)_Income', 'No'), 0.27633069082672707),
 (('3_ESat', 'No'), 0.2865232163080408),
 (('3_RSat', 'No'), 0.2865232163080408),
 (('3_JSat', 'No'), 0.28199320498301245),
 (('[1009.0, 3607.8)_Income', 'No'), 0.2955832389580974),
 (('[1.0, 3.8)_Distance', 'No'), 0.3250283125707814),
 (('[32.0, 39.0)_Age', 'Travel_Rarely'), 0.2536806342015855),
 (('[32.0, 39.0)_Age', 'No'), 0.3261608154020385),
 (('Yes', 'Travel_Rarely'), 0.2650056625141563),
 (('Yes', 'No'), 0.2695356738391846),
 (('MidLevel', 'Travel_Rarely'), 0.26840317100792754),
 (('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('MidLevel', 'No'), 0.35334088335220837),
 (('1_companies', '3_WLBalance'), 0.25141562853907135),
 (('1_companies', 'Travel_Rarely'), 0.29331823329558326),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('1_companies', 'No'), 0.34428086070215175),
 (('Female', 'Travel_Rarely'), 0.2876557191392978),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('Female', 'No'), 0.35334088335220837),
 (('1_stockOption', 'Travel_Rarely'), 0.2808607021517554),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('1_stockOption', 'No'), 0.36806342015855037),
 (('Bachelor', 'Male'), 0.25141562853907135),
 (('Bachelor', 'Travel_Rarely'), 0.3171007927519819),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('Bachelor', 'No'), 0.3635334088335221),
 (('EntryLevel', 'Travel_Rarely'), 0.3001132502831257),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('EntryLevel', 'No'), 0.3488108720271801),
 (('[11.0, 13.8)_%', 'Male'), 0.26727066817667045),
 (('[11.0, 13.8)_%', 'Travel_Rarely'), 0.3035107587768969),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('[11.0, 13.8)_%', 'No'), 0.3725934314835787),
 (('0_stockOption', '3_JIvol'), 0.25141562853907135),
 (('0_stockOption', '3_WLBalance'), 0.2695356738391846),
 (('0_stockOption', 'Male'), 0.28312570781426954),
 (('0_stockOption', 'Travel_Rarely'), 0.3159682899207248),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', 'No'), 0.38052095130237823),
 (('2.0_Time', '3_JIvol'), 0.27746319365798416),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', '3_WLBalance'), 0.26613816534541335),
 (('2.0_Time', 'Male'), 0.30804077010192527),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely'), 0.3510758776896942),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('2.0_Time', 'No'), 0.4269535673839185),
 (('3_JIvol', '3_WLBalance'), 0.3510758776896942),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male'), 0.3635334088335221),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely'), 0.41562853907134767),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_JIvol', 'No'), 0.535673839184598),
 (('3_WLBalance', 'Male'), 0.3646659116647792),
 (('3_WLBalance', 'Male', 'Travel_Rarely'), 0.2718006795016987),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('3_WLBalance', 'Male', 'No'), 0.3318233295583239),
 (('3_WLBalance', 'Travel_Rarely'), 0.45866364665911663),
 (('3_WLBalance', 'Travel_Rarely', 'No'), 0.4178935447338618),
 (('3_WLBalance', 'No'), 0.5526613816534541),
 (('Male', 'Travel_Rarely'), 0.44620611551528877),
 (('Male', 'Travel_Rarely', 'No'), 0.40656851642129105),
 (('Male', 'No'), 0.5560588901472253),
 (('Travel_Rarely', 'No'), 0.665911664779162)]

In [38]:
itemsets1 = apriori(baskets, supp=25, report ='s', target='a',zmin = 3)
print('Number of itemsets:', len(itemsets1))
itemsets1

Number of itemsets: 21

[(('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_WLBalance', 'Male', 'Travel_Rarely'), 0.2718006795016987),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('3_WLBalance', 'Male', 'No'), 0.3318233295583239),
 (('3_WLBalance', 'Travel_Rarely', 'No'), 0.4178935447338618),
 (('Male', 'Travel_Rarely', 'No'), 0.40656851642129105)]

In [39]:
itemsets2 = apriori(baskets, supp=25, report ='s', target='a',zmin = 4)
print('Number of itemsets:', len(itemsets2))
itemsets2

Number of itemsets: 1

[(('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425)]

Maximal Itemset with min value 2/3/4

In [40]:
itemsets3 = apriori(baskets, supp=25, report ='s', target='m',zmin = 2)
print('Number of itemsets:', len(itemsets3))
itemsets3

Number of itemsets: 38

[(('3.0_Time', 'No'), 0.2582106455266138),
 (('4_ESat', 'No'), 0.26160815402038506),
 (('4_JSat', 'No'), 0.27519818799546997),
 (('4_RSat', 'No'), 0.26840317100792754),
 (('[3607.8, 6206.6)_Income', 'No'), 0.27633069082672707),
 (('3_ESat', 'No'), 0.2865232163080408),
 (('3_RSat', 'No'), 0.2865232163080408),
 (('3_JSat', 'No'), 0.28199320498301245),
 (('[1009.0, 3607.8)_Income', 'No'), 0.2955832389580974),
 (('[1.0, 3.8)_Distance', 'No'), 0.3250283125707814),
 (('[32.0, 39.0)_Age', 'Travel_Rarely'), 0.2536806342015855),
 (('[32.0, 39.0)_Age', 'No'), 0.3261608154020385),
 (('Yes', 'Travel_Rarely'), 0.2650056625141563),
 (('Yes', 'No'), 0.2695356738391846),
 (('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_companies', '3_WLBalance'), 0.25141562853907135),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('Bachelor', 'Male'), 0.25141562853907135),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('[11.0, 13.8)_%', 'Male'), 0.26727066817667045),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', '3_JIvol'), 0.25141562853907135),
 (('0_stockOption', '3_WLBalance'), 0.2695356738391846),
 (('0_stockOption', 'Male'), 0.28312570781426954),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', '3_WLBalance'), 0.26613816534541335),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425)]

In [41]:
itemsets4 = apriori(baskets, supp=25, report ='s', target='m',zmin = 3)
print('Number of itemsets:', len(itemsets4))
itemsets4

Number of itemsets: 17

[(('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425)]

In [42]:
itemsets5 = apriori(baskets, supp=25, report ='s', target='m',zmin = 4)
print('Number of itemsets:', len(itemsets5))
itemsets5

Number of itemsets: 1

[(('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425)]

Closed Itemset with min value 2/3/4

In [43]:
itemsets6 = apriori(baskets, supp=25, report ='s', target='c',zmin = 2)
print('Number of itemsets:', len(itemsets6))
itemsets6

Number of itemsets: 72

[(('3.0_Time', 'No'), 0.2582106455266138),
 (('4_ESat', 'No'), 0.26160815402038506),
 (('4_JSat', 'No'), 0.27519818799546997),
 (('4_RSat', 'No'), 0.26840317100792754),
 (('[3607.8, 6206.6)_Income', 'No'), 0.27633069082672707),
 (('3_ESat', 'No'), 0.2865232163080408),
 (('3_RSat', 'No'), 0.2865232163080408),
 (('3_JSat', 'No'), 0.28199320498301245),
 (('[1009.0, 3607.8)_Income', 'No'), 0.2955832389580974),
 (('[1.0, 3.8)_Distance', 'No'), 0.3250283125707814),
 (('[32.0, 39.0)_Age', 'Travel_Rarely'), 0.2536806342015855),
 (('[32.0, 39.0)_Age', 'No'), 0.3261608154020385),
 (('Yes', 'Travel_Rarely'), 0.2650056625141563),
 (('Yes', 'No'), 0.2695356738391846),
 (('MidLevel', 'Travel_Rarely'), 0.26840317100792754),
 (('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('MidLevel', 'No'), 0.35334088335220837),
 (('1_companies', '3_WLBalance'), 0.25141562853907135),
 (('1_companies', 'Travel_Rarely'), 0.29331823329558326),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('1_companies', 'No'), 0.34428086070215175),
 (('Female', 'Travel_Rarely'), 0.2876557191392978),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('Female', 'No'), 0.35334088335220837),
 (('1_stockOption', 'Travel_Rarely'), 0.2808607021517554),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('1_stockOption', 'No'), 0.36806342015855037),
 (('Bachelor', 'Male'), 0.25141562853907135),
 (('Bachelor', 'Travel_Rarely'), 0.3171007927519819),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('Bachelor', 'No'), 0.3635334088335221),
 (('EntryLevel', 'Travel_Rarely'), 0.3001132502831257),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('EntryLevel', 'No'), 0.3488108720271801),
 (('[11.0, 13.8)_%', 'Male'), 0.26727066817667045),
 (('[11.0, 13.8)_%', 'Travel_Rarely'), 0.3035107587768969),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('[11.0, 13.8)_%', 'No'), 0.3725934314835787),
 (('0_stockOption', '3_JIvol'), 0.25141562853907135),
 (('0_stockOption', '3_WLBalance'), 0.2695356738391846),
 (('0_stockOption', 'Male'), 0.28312570781426954),
 (('0_stockOption', 'Travel_Rarely'), 0.3159682899207248),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', 'No'), 0.38052095130237823),
 (('2.0_Time', '3_JIvol'), 0.27746319365798416),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', '3_WLBalance'), 0.26613816534541335),
 (('2.0_Time', 'Male'), 0.30804077010192527),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely'), 0.3510758776896942),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('2.0_Time', 'No'), 0.4269535673839185),
 (('3_JIvol', '3_WLBalance'), 0.3510758776896942),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male'), 0.3635334088335221),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely'), 0.41562853907134767),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_JIvol', 'No'), 0.535673839184598),
 (('3_WLBalance', 'Male'), 0.3646659116647792),
 (('3_WLBalance', 'Male', 'Travel_Rarely'), 0.2718006795016987),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('3_WLBalance', 'Male', 'No'), 0.3318233295583239),
 (('3_WLBalance', 'Travel_Rarely'), 0.45866364665911663),
 (('3_WLBalance', 'Travel_Rarely', 'No'), 0.4178935447338618),
 (('3_WLBalance', 'No'), 0.5526613816534541),
 (('Male', 'Travel_Rarely'), 0.44620611551528877),
 (('Male', 'Travel_Rarely', 'No'), 0.40656851642129105),
 (('Male', 'No'), 0.5560588901472253),
 (('Travel_Rarely', 'No'), 0.665911664779162)]

In [44]:
itemsets7 = apriori(baskets, supp=25, report ='s', target='c',zmin = 3)
print('Number of itemsets:', len(itemsets7))
itemsets7

Number of itemsets: 21

[(('MidLevel', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_companies', 'Travel_Rarely', 'No'), 0.26160815402038506),
 (('Female', 'Travel_Rarely', 'No'), 0.25934314835787087),
 (('1_stockOption', 'Travel_Rarely', 'No'), 0.26613816534541335),
 (('Bachelor', 'Travel_Rarely', 'No'), 0.28312570781426954),
 (('EntryLevel', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('[11.0, 13.8)_%', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('0_stockOption', 'Travel_Rarely', 'No'), 0.2718006795016987),
 (('2.0_Time', '3_JIvol', 'No'), 0.2536806342015855),
 (('2.0_Time', 'Male', 'No'), 0.27519818799546997),
 (('2.0_Time', 'Travel_Rarely', 'No'), 0.3114382785956965),
 (('3_JIvol', '3_WLBalance', 'Travel_Rarely'), 0.26160815402038506),
 (('3_JIvol', '3_WLBalance', 'No'), 0.32842582106455265),
 (('3_JIvol', 'Male', 'Travel_Rarely'), 0.2548131370328426),
 (('3_JIvol', 'Male', 'No'), 0.33748584371460927),
 (('3_JIvol', 'Travel_Rarely', 'No'), 0.38052095130237823),
 (('3_WLBalance', 'Male', 'Travel_Rarely'), 0.2718006795016987),
 (('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425),
 (('3_WLBalance', 'Male', 'No'), 0.3318233295583239),
 (('3_WLBalance', 'Travel_Rarely', 'No'), 0.4178935447338618),
 (('Male', 'Travel_Rarely', 'No'), 0.40656851642129105)]

In [45]:
itemsets8 = apriori(baskets, supp=25, report ='s', target='c',zmin = 4)
print('Number of itemsets:', len(itemsets8))
itemsets8

Number of itemsets: 1

[(('3_WLBalance', 'Male', 'Travel_Rarely', 'No'), 0.25028312570781425)]

# Considerazioni finali

Un valore di supporto elevato non permette di catturare molte associazioni significative, viceversa un valore troppo basso
porta ad un numero elevato di itemset ed a una difficile analisi con 50 e 60

In [46]:
print('Numeber of itemset with support = 25')
print ('Target Frequent')
print('Number of itemsets [2]:', len(itemsets))
print('Number of itemsets [3]:', len(itemsets1))
print('Number of itemsets [4]:', len(itemsets2))
print ('Target Maximum')
print('Number of itemsets [2]:', len(itemsets3))
print('Number of itemsets [3]:', len(itemsets4))
print('Number of itemsets [4]:', len(itemsets5))
print('Target Closed')
print('Number of itemsets [2]:', len(itemsets6))
print('Number of itemsets [3]:', len(itemsets7))
print('Number of itemsets [4]:', len(itemsets8))

Numeber of itemset with support = 25
Target Frequent
Number of itemsets [2]: 72
Number of itemsets [3]: 21
Number of itemsets [4]: 1
Target Maximum
Number of itemsets [2]: 38
Number of itemsets [3]: 17
Number of itemsets [4]: 1
Target Closed
Number of itemsets [2]: 72
Number of itemsets [3]: 21
Number of itemsets [4]: 1

# Association Rules zmin = 2

In [47]:
rules = apriori(baskets, supp=25, zmin=2, target='r', conf=60, 
                report='ascl') 
print('Number of rule:', len(rules))
set(rules)

Number of rule: 258

{('3_JIvol',
  ('1_stockOption',),
  207,
  0.23442808607021517,
  0.6017441860465116,
  1.0377736646075582),
 ('3_JIvol',
  ('1_stockOption', 'No'),
  197,
  0.22310305775764439,
  0.6061538461538462,
  1.0453786057692307),
 ('3_JIvol',
  ('2_YearsInCurrentRole',),
  155,
  0.1755379388448471,
  0.6352459016393442,
  1.095551037397541),
 ('3_JIvol',
  ('3_JSat', 'No'),
  152,
  0.17214043035107587,
  0.6104417670682731,
  1.05277359437751),
 ('3_JIvol',
  ('3_RSat',),
  169,
  0.1913929784824462,
  0.6123188405797102,
  1.0560108129528984),
 ('3_JIvol',
  ('3_RSat', 'No'),
  155,
  0.1755379388448471,
  0.6126482213438735,
  1.0565788661067195),
 ('3_JIvol',
  ('3_WLBalance', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6143344709897611,
  1.0594869880546076),
 ('3_JIvol',
  ('4_ESat',),
  153,
  0.17327293318233294,
  0.6023622047244095,
  1.0388395054133859),
 ('3_JIvol',
  ('4_ESat', 'No'),
  141,
  0.159682899207248,
  0.6103896103896104,
  1.0526836444805194),
 ('3_JIvol',
  ('4_JSat',),
  158,
  0.17893544733861835,
  0.6124031007751938,
  1.056156128875969),
 ('3_JIvol',
  ('4_JSat', 'No'),
  149,
  0.16874292185730463,
  0.6131687242798354,
  1.0574765303497942),
 ('3_JIvol',
  ('Male', 'No'),
  298,
  0.33748584371460927,
  0.6069246435845214,
  1.0467079302443991),
 ('3_JIvol',
  ('Master',),
  141,
  0.159682899207248,
  0.6294642857142857,
  1.0855800083705358),
 ('3_JIvol',
  ('[3607.8, 6206.6)_Income',),
  159,
  0.18006795016987542,
  0.6,
  1.034765625),
 ('3_JIvol',
  ('[3607.8, 6206.6)_Income', 'No'),
  149,
  0.16874292185730463,
  0.610655737704918,
  1.0531426101434427),
 ('3_WLBalance',
  ('0_stockOption',),
  238,
  0.2695356738391846,
  0.6149870801033591,
  1.0150160593107778),
 ('3_WLBalance',
  ('0_stockOption', '3_JIvol'),
  141,
  0.159682899207248,
  0.6351351351351351,
  1.048269765092195),
 ('3_WLBalance',
  ('0_stockOption', 'Male'),
  151,
  0.1710079275198188,
  0.604,
  0.9968822429906542),
 ('3_WLBalance',
  ('0_stockOption', 'No'),
  211,
  0.23895809739524349,
  0.6279761904761905,
  1.0364541611036937),
 ('3_WLBalance',
  ('0_stockOption', 'Travel_Rarely'),
  176,
  0.19932049830124576,
  0.6308243727598566,
  1.0411549927980437),
 ('3_WLBalance',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  154,
  0.17440543601359004,
  0.6416666666666667,
  1.0590498442367602),
 ('3_WLBalance',
  ('1_companies',),
  222,
  0.25141562853907135,
  0.6548672566371682,
  1.0808369861880738),
 ('3_WLBalance',
  ('1_companies', 'No'),
  201,
  0.2276330690826727,
  0.6611842105263158,
  1.0912629119527792),
 ('3_WLBalance',
  ('1_companies', 'Travel_Rarely'),
  173,
  0.19592298980747452,
  0.667953667953668,
  1.1024356800057735),
 ('3_WLBalance',
  ('1_companies', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.670995670995671,
  1.107456406521827),
 ('3_WLBalance',
  ('1_stockOption', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6008064516129032,
  0.9916113958396141),
 ('3_WLBalance',
  ('1_stockOption', 'Travel_Rarely', 'No'),
  142,
  0.16081540203850508,
  0.6042553191489362,
  0.9973036388944124),
 ('3_WLBalance',
  ('2_YearsInCurrentRole',),
  157,
  0.17780294450736125,
  0.6434426229508197,
  1.0619810019917266),
 ('3_WLBalance',
  ('3.0_Time',),
  160,
  0.1812004530011325,
  0.6477732793522267,
  1.0691286087252638),
 ('3_WLBalance',
  ('3.0_Time', 'No'),
  148,
  0.16761041902604756,
  0.6491228070175439,
  1.0713559599934415),
 ('3_WLBalance',
  ('3_ESat',),
  167,
  0.18912797281993204,
  0.6117216117216118,
  1.00962651056109),
 ('3_WLBalance',
  ('3_ESat', 'No'),
  153,
  0.17327293318233294,
  0.6047430830039525,
  0.9981086771822245),
 ('3_WLBalance',
  ('3_JIvol',),
  310,
  0.3510758776896942,
  0.60546875,
  0.9993063668224299),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6040268456375839,
  0.996926550837358),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6177777777777778,
  1.0196220145379025),
 ('3_WLBalance',
  ('3_JIvol', 'No'),
  290,
  0.32842582106455265,
  0.6131078224101479,
  1.011914405959179),
 ('3_WLBalance',
  ('3_JIvol', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.6294277929155313,
  1.0388499834475031),
 ('3_WLBalance',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  215,
  0.2434881087202718,
  0.6398809523809523,
  1.0561025812194036),
 ('3_WLBalance',
  ('3_JSat',),
  175,
  0.19818799546998866,
  0.6340579710144928,
  1.0464919409454152),
 ('3_WLBalance',
  ('3_JSat', 'No'),
  156,
  0.17667044167610418,
  0.6265060240963856,
  1.0340276995833801),
 ('3_WLBalance',
  ('3_RSat',),
  169,
  0.1913929784824462,
  0.6123188405797102,
  1.010612217255858),
 ('3_WLBalance',
  ('3_RSat', 'No'),
  155,
  0.1755379388448471,
  0.6126482213438735,
  1.0111558494329727),
 ('3_WLBalance',
  ('4_ESat',),
  159,
  0.18006795016987542,
  0.6259842519685039,
  1.0331665317536243),
 ('3_WLBalance',
  ('4_ESat', 'No'),
  147,
  0.1664779161947905,
  0.6363636363636364,
  1.0502973661852166),
 ('3_WLBalance',
  ('4_RSat',),
  164,
  0.1857304643261608,
  0.6307692307692307,
  1.0410639827462258),
 ('3_WLBalance',
  ('4_RSat', 'No'),
  152,
  0.17214043035107587,
  0.6413502109704642,
  1.0585275444615323),
 ('3_WLBalance',
  ('Bachelor',),
  216,
  0.24462061155152887,
  0.6016713091922006,
  0.9930388149845104),
 ('3_WLBalance',
  ('Bachelor', 'No'),
  193,
  0.21857304643261607,
  0.6012461059190031,
  0.9923370308906163),
 ('3_WLBalance',
  ('Bachelor', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.6214285714285714,
  1.0256475300400534),
 ('3_WLBalance',
  ('Bachelor', 'Travel_Rarely', 'No'),
  157,
  0.17780294450736125,
  0.628,
  1.0364934579439253),
 ('3_WLBalance',
  ('EntryLevel', 'No'),
  187,
  0.21177802944507362,
  0.6071428571428571,
  1.0020694259012015),
 ('3_WLBalance',
  ('EntryLevel', 'Travel_Rarely', 'No'),
  133,
  0.1506228765571914,
  0.6018099547511312,
  0.9932676449443905),
 ('3_WLBalance',
  ('Female',),
  213,
  0.24122310305775765,
  0.6209912536443148,
  1.0249257513419252),
 ('3_WLBalance',
  ('Female', 'No'),
  195,
  0.22083805209513024,
  0.625,
  1.0315420560747663),
 ('3_WLBalance',
  ('Female', 'Travel_Rarely'),
  165,
  0.1868629671574179,
  0.6496062992125984,
  1.072153948046214),
 ('3_WLBalance',
  ('Female', 'Travel_Rarely', 'No'),
  148,
  0.16761041902604756,
  0.6462882096069869,
  1.0666775496877934),
 ('3_WLBalance',
  ('Male', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.6091370558375635,
  1.005360785616016),
 ('3_WLBalance',
  ('Male', 'Travel_Rarely', 'No'),
  221,
  0.25028312570781425,
  0.6155988857938719,
  1.0160258245906333),
 ('3_WLBalance',
  ('Master',),
  135,
  0.15288788221970556,
  0.6026785714285714,
  0.9947012683578104),
 ('3_WLBalance',
  ('MidLevel',),
  197,
  0.22310305775764439,
  0.6061538461538462,
  1.0004370956146658),
 ('3_WLBalance',
  ('MidLevel', 'No'),
  188,
  0.2129105322763307,
  0.6025641025641025,
  0.9945123412413132),
 ('3_WLBalance',
  ('MidLevel', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0376355534524233),
 ('3_WLBalance',
  ('MidLevel', 'Travel_Rarely', 'No'),
  143,
  0.16194790486976218,
  0.6244541484716157,
  1.0306411459821245),
 ('3_WLBalance',
  ('No',),
  488,
  0.5526613816534541,
  0.6077210460772104,
  1.0030237078246296),
 ('3_WLBalance',
  ('Travel_Rarely',),
  405,
  0.45866364665911663,
  0.625,
  1.0315420560747663),
 ('3_WLBalance',
  ('Travel_Rarely', 'No'),
  369,
  0.4178935447338618,
  0.6275510204081632,
  1.0357524318138471),
 ('3_WLBalance',
  ('Yes', 'No'),
  143,
  0.16194790486976218,
  0.6008403361344538,
  0.9916673211340611),
 ('3_WLBalance',
  ('Yes', 'Travel_Rarely'),
  142,
  0.16081540203850508,
  0.6068376068376068,
  1.001565620257209),
 ('3_WLBalance',
  ('[1009.0, 3607.8)_Income',),
  170,
  0.19252548131370328,
  0.6071428571428571,
  1.0020694259012015),
 ('3_WLBalance',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  161,
  0.1823329558323896,
  0.6007462686567164,
  0.9915120658390292),
 ('3_WLBalance',
  ('[13.8, 16.6)_%',),
  142,
  0.16081540203850508,
  0.6200873362445415,
  1.023433865240991),
 ('3_WLBalance',
  ('[25.0, 32.0)_Age',),
  138,
  0.15628539071347677,
  0.6188340807174888,
  1.0213654079879302),
 ('3_WLBalance',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  137,
  0.1551528878822197,
  0.6116071428571429,
  1.0094375834445928),
 ('Male',
  ('0_stockOption',),
  250,
  0.28312570781426954,
  0.6459948320413437,
  1.0563211790601972),
 ('Male',
  ('0_stockOption', '3_JIvol'),
  147,
  0.1664779161947905,
  0.6621621621621622,
  1.0827577577577578),
 ('Male',
  ('0_stockOption', '3_WLBalance'),
  151,
  0.1710079275198188,
  0.634453781512605,
  1.0374494242141301),
 ('Male',
  ('0_stockOption', 'No'),
  218,
  0.24688561721404303,
  0.6488095238095238,
  1.060923721340388),
 ('Male',
  ('0_stockOption', 'Travel_Rarely'),
  181,
  0.20498301245753114,
  0.6487455197132617,
  1.0608190627903888),
 ('Male',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  156,
  0.17667044167610418,
  0.65,
  1.0628703703703704),
 ('Male',
  ('1_companies',),
  213,
  0.24122310305775765,
  0.6283185840707964,
  1.0274172402490986),
 ('Male',
  ('1_companies', '3_WLBalance'),
  140,
  0.15855039637599094,
  0.6306306306306306,
  1.0311978645311979),
 ('Male',
  ('1_companies', 'No'),
  191,
  0.21630804077010193,
  0.6282894736842105,
  1.0273696393762184),
 ('Male',
  ('1_companies', 'Travel_Rarely'),
  162,
  0.18346545866364666,
  0.6254826254826255,
  1.0227799227799228),
 ('Male',
  ('1_companies', 'Travel_Rarely', 'No'),
  145,
  0.16421291053227632,
  0.6277056277056277,
  1.0264149430816099),
 ('Male',
  ('2.0_Time',),
  272,
  0.30804077010192527,
  0.6430260047281324,
  1.051466596620261),
 ('Male',
  ('2.0_Time', '3_JIvol'),
  156,
  0.17667044167610418,
  0.636734693877551,
  1.0411791383219955),
 ('Male',
  ('2.0_Time', '3_JIvol', 'No'),
  142,
  0.16081540203850508,
  0.6339285714285714,
  1.0365906084656085),
 ('Male',
  ('2.0_Time', '3_WLBalance'),
  155,
  0.1755379388448471,
  0.6595744680851063,
  1.0785263987391647),
 ('Male',
  ('2.0_Time', 'No'),
  243,
  0.27519818799546997,
  0.6445623342175066,
  1.0539787798408489),
 ('Male',
  ('2.0_Time', 'Travel_Rarely'),
  200,
  0.22650056625141562,
  0.6451612903225806,
  1.054958183990442),
 ('Male',
  ('2.0_Time', 'Travel_Rarely', 'No'),
  179,
  0.20271800679501698,
  0.6509090909090909,
  1.0643569023569024),
 ('Male',
  ('2_YearsInCurrentRole',),
  148,
  0.16761041902604756,
  0.6065573770491803,
  0.9918336369156041),
 ('Male',
  ('3_ESat',),
  169,
  0.1913929784824462,
  0.6190476190476191,
  1.012257495590829),
 ('Male',
  ('3_ESat', 'No'),
  157,
  0.17780294450736125,
  0.6205533596837944,
  1.0147196603718343),
 ('Male',
  ('3_JIvol',),
  321,
  0.3635334088335221,
  0.626953125,
  1.0251844618055554),
 ('Male',
  ('3_JIvol', '3_WLBalance'),
  192,
  0.217440543601359,
  0.6193548387096774,
  1.0127598566308245),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'No'),
  180,
  0.20385050962627407,
  0.6206896551724138,
  1.0149425287356322),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6017316017316018,
  0.9839426006092673),
 ('Male',
  ('3_JIvol', 'No'),
  298,
  0.33748584371460927,
  0.6300211416490487,
  1.0302012371779814),
 ('Male',
  ('3_JIvol', 'Travel_Rarely'),
  225,
  0.2548131370328426,
  0.6130790190735694,
  1.0024977293369663),
 ('Male',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  207,
  0.23442808607021517,
  0.6160714285714286,
  1.007390873015873),
 ('Male',
  ('3_RSat',),
  171,
  0.19365798414496035,
  0.6195652173913043,
  1.0131038647342996),
 ('Male',
  ('3_RSat', 'No'),
  157,
  0.17780294450736125,
  0.6205533596837944,
  1.0147196603718343),
 ('Male',
  ('3_WLBalance',),
  322,
  0.3646659116647792,
  0.6018691588785047,
  0.9841675320179993),
 ('Male',
  ('3_WLBalance', 'No'),
  293,
  0.3318233295583239,
  0.6004098360655737,
  0.981781268973892),
 ('Male',
  ('4_RSat',),
  162,
  0.18346545866364666,
  0.6230769230769231,
  1.018846153846154),
 ('Male',
  ('4_RSat', 'No'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0280278168463823),
 ('Male',
  ('Bachelor',),
  222,
  0.25141562853907135,
  0.6183844011142061,
  1.011173011451563),
 ('Male',
  ('Bachelor', 'No'),
  200,
  0.22650056625141562,
  0.6230529595015576,
  1.0188069689627322),
 ('Male',
  ('Bachelor', 'Travel_Rarely'),
  171,
  0.19365798414496035,
  0.6107142857142858,
  0.9986309523809523),
 ('Male',
  ('Bachelor', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.62,
  1.0138148148148147),
 ('Male',
  ('Master',),
  137,
  0.1551528878822197,
  0.6116071428571429,
  1.0000909391534392),
 ('Male',
  ('MidLevel',),
  200,
  0.22650056625141562,
  0.6153846153846154,
  1.0062678062678063),
 ('Male',
  ('MidLevel', 'No'),
  192,
  0.217440543601359,
  0.6153846153846154,
  1.0062678062678063),
 ('Male',
  ('MidLevel', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0280278168463823),
 ('Male',
  ('MidLevel', 'Travel_Rarely', 'No'),
  144,
  0.16308040770101925,
  0.62882096069869,
  1.0282387190684135),
 ('Male',
  ('No',),
  491,
  0.5560588901472253,
  0.6114570361145704,
  0.9998454868317882),
 ('Male',
  ('Travel_Rarely',),
  394,
  0.44620611551528877,
  0.6080246913580247,
  0.9942329675354367),
 ('Male',
  ('Travel_Rarely', 'No'),
  359,
  0.40656851642129105,
  0.6105442176870748,
  0.9983528596623835),
 ('Male',
  ('Yes',),
  194,
  0.21970554926387317,
  0.610062893081761,
  0.9975658047985092),
 ('Male',
  ('Yes', 'No'),
  145,
  0.16421291053227632,
  0.6092436974789915,
  0.9962262682850919),
 ('Male',
  ('[1.0, 3.8)_Distance',),
  189,
  0.21404303510758776,
  0.6077170418006431,
  0.9937299035369775),
 ('Male',
  ('[1.0, 3.8)_Distance', 'No'),
  175,
  0.19818799546998866,
  0.6097560975609756,
  0.9970641373080398),
 ('Male',
  ('[1009.0, 3607.8)_Income',),
  187,
  0.21177802944507362,
  0.6678571428571428,
  1.0920701058201059),
 ('Male',
  ('[1009.0, 3607.8)_Income', 'No'),
  175,
  0.19818799546998866,
  0.6704980842911877,
  1.0963885341279977),
 ('Male',
  ('[11.0, 13.8)_%',),
  236,
  0.26727066817667045,
  0.6465753424657534,
  1.0572704211060375),
 ('Male',
  ('[11.0, 13.8)_%', 'No'),
  212,
  0.24009060022650056,
  0.6443768996960486,
  1.0536755600585388),
 ('Male',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  176,
  0.19932049830124576,
  0.6567164179104478,
  1.073852957435047),
 ('Male',
  ('[11.0, 13.8)_%', 'Travel_Rarely', 'No'),
  158,
  0.17893544733861835,
  0.6583333333333333,
  1.076496913580247),
 ('Male',
  ('[25.0, 32.0)_Age',),
  135,
  0.15288788221970556,
  0.6053811659192825,
  0.9899103139013453),
 ('No',
  ('0_stockOption',),
  336,
  0.38052095130237823,
  0.8682170542635659,
  0.954714394663423),
 ('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies',),
  304,
  0.34428086070215175,
  0.8967551622418879,
  0.986095651630868),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption',),
  325,
  0.36806342015855037,
  0.9447674418604651,
  1.0388912218714703),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time',),
  377,
  0.4269535673839185,
  0.8912529550827423,
  0.9800452793749209),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('2_YearsInCurrentRole',),
  219,
  0.2480181200453001,
  0.8975409836065574,
  0.9869597615499255),
 ('No',
  ('3.0_Time',),
  228,
  0.2582106455266138,
  0.9230769230769231,
  1.0150397547657821),
 ('No',
  ('3_ESat',),
  253,
  0.2865232163080408,
  0.9267399267399268,
  1.019067690300567),
 ('No', ('3_JIvol',), 473, 0.535673839184598, 0.923828125, 1.0158657962328768),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_JSat',),
  249,
  0.28199320498301245,
  0.9021739130434783,
  0.9920542530727164),
 ('No',
  ('3_RSat',),
  253,
  0.2865232163080408,
  0.9166666666666666,
  1.0079908675799087),
 ('No',
  ('3_WLBalance',),
  488,
  0.5526613816534541,
  0.9121495327102803,
  1.0030237078246296),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('4_ESat',),
  231,
  0.26160815402038506,
  0.9094488188976378,
  1.0000539316147126),
 ('No',
  ('4_JSat',),
  243,
  0.27519818799546997,
  0.9418604651162791,
  1.0356946334964812),
 ('No',
  ('4_RSat',),
  237,
  0.26840317100792754,
  0.9115384615384615,
  1.0023517578312098),
 ('No',
  ('Bachelor',),
  321,
  0.3635334088335221,
  0.8941504178272981,
  0.9832314059047375),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel',),
  308,
  0.3488108720271801,
  0.8461538461538461,
  0.9304531085353003),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female',),
  312,
  0.35334088335220837,
  0.9096209912536443,
  1.000243256882899),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male',),
  491,
  0.5560588901472253,
  0.9092592592592592,
  0.9998454868317882),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('Master',),
  209,
  0.23669309173272934,
  0.9330357142857143,
  1.0259907045009784),
 ('No', ('MidLevel',), 312, 0.35334088335220837, 0.96, 1.0556413449564135),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Travel_Rarely',),
  588,
  0.665911664779162,
  0.9074074074074074,
  0.9978091416447581),
 ('No',
  ('Yes',),
  238,
  0.2695356738391846,
  0.7484276729559748,
  0.8229908284185875),
 ('No',
  ('Yes', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.7435897435897436,
  0.8176709135613245),
 ('No',
  ('[1.0, 3.8)_Distance',),
  287,
  0.3250283125707814,
  0.9228295819935691,
  1.014767771980475),

In [48]:
rules1 = apriori(baskets, supp=25, zmin=2, target='r', conf=70, 
                report='ascl') 
print('Number of rule:', len(rules1))
set(rules1)

Number of rule: 117

{('No',
  ('0_stockOption',),
  336,
  0.38052095130237823,
  0.8682170542635659,
  0.954714394663423),
 ('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies',),
  304,
  0.34428086070215175,
  0.8967551622418879,
  0.986095651630868),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption',),
  325,
  0.36806342015855037,
  0.9447674418604651,
  1.0388912218714703),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time',),
  377,
  0.4269535673839185,
  0.8912529550827423,
  0.9800452793749209),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('2_YearsInCurrentRole',),
  219,
  0.2480181200453001,
  0.8975409836065574,
  0.9869597615499255),
 ('No',
  ('3.0_Time',),
  228,
  0.2582106455266138,
  0.9230769230769231,
  1.0150397547657821),
 ('No',
  ('3_ESat',),
  253,
  0.2865232163080408,
  0.9267399267399268,
  1.019067690300567),
 ('No', ('3_JIvol',), 473, 0.535673839184598, 0.923828125, 1.0158657962328768),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_JSat',),
  249,
  0.28199320498301245,
  0.9021739130434783,
  0.9920542530727164),
 ('No',
  ('3_RSat',),
  253,
  0.2865232163080408,
  0.9166666666666666,
  1.0079908675799087),
 ('No',
  ('3_WLBalance',),
  488,
  0.5526613816534541,
  0.9121495327102803,
  1.0030237078246296),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('4_ESat',),
  231,
  0.26160815402038506,
  0.9094488188976378,
  1.0000539316147126),
 ('No',
  ('4_JSat',),
  243,
  0.27519818799546997,
  0.9418604651162791,
  1.0356946334964812),
 ('No',
  ('4_RSat',),
  237,
  0.26840317100792754,
  0.9115384615384615,
  1.0023517578312098),
 ('No',
  ('Bachelor',),
  321,
  0.3635334088335221,
  0.8941504178272981,
  0.9832314059047375),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel',),
  308,
  0.3488108720271801,
  0.8461538461538461,
  0.9304531085353003),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female',),
  312,
  0.35334088335220837,
  0.9096209912536443,
  1.000243256882899),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male',),
  491,
  0.5560588901472253,
  0.9092592592592592,
  0.9998454868317882),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('Master',),
  209,
  0.23669309173272934,
  0.9330357142857143,
  1.0259907045009784),
 ('No', ('MidLevel',), 312, 0.35334088335220837, 0.96, 1.0556413449564135),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Travel_Rarely',),
  588,
  0.665911664779162,
  0.9074074074074074,
  0.9978091416447581),
 ('No',
  ('Yes',),
  238,
  0.2695356738391846,
  0.7484276729559748,
  0.8229908284185875),
 ('No',
  ('Yes', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.7435897435897436,
  0.8176709135613245),
 ('No',
  ('[1.0, 3.8)_Distance',),
  287,
  0.3250283125707814,
  0.9228295819935691,
  1.014767771980475),
 ('No',
  ('[1009.0, 3607.8)_Income',),
  261,
  0.2955832389580974,
  0.9321428571428572,
  1.0250088952143748),
 ('No',
  ('[11.0, 13.8)_%',),
  329,
  0.3725934314835787,
  0.9013698630136986,
  0.9911700984322489),
 ('No',
  ('[11.0, 13.8)_%', 'Male'),
  212,
  0.24009060022650056,
  0.8983050847457628,
  0.987799987335627),
 ('No',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8955223880597015,
  0.9847400605936693),
 ('No',
  ('[13.8, 16.6)_%',),
  209,
  0.23669309173272934,
  0.9126637554585153,
  1.0035891607345815),
 ('No',
  ('[25.0, 32.0)_Age',),
  200,
  0.22650056625141562,
  0.8968609865470852,
  0.9862120188307301),
 ('No',
  ('[32.0, 39.0)_Age',),
  288,
  0.3261608154020385,
  0.9201277955271565,
  1.0117968162521536),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403),
 ('No',
  ('[3607.8, 6206.6)_Income',),
  244,
  0.27633069082672707,
  0.9207547169811321,
  1.0124861956342959),
 ('Travel_Rarely',
  ('0_stockOption',),
  279,
  0.3159682899207248,
  0.7209302325581395,
  0.9823786965259833),
 ('Travel_Rarely',
  ('0_stockOption', '3_JIvol'),
  159,
  0.18006795016987542,
  0.7162162162162162,
  0.9759551217884551),
 ('Travel_Rarely',
  ('0_stockOption', '3_WLBalance'),
  176,
  0.19932049830124576,
  0.7394957983193278,
  1.007677144932047),
 ('Travel_Rarely',
  ('0_stockOption', 'Male'),
  181,
  0.20498301245753114,
  0.724,
  0.9865617283950617),
 ('Travel_Rarely',
  ('0_stockOption', 'No'),
  240,
  0.2718006795016987,
  0.7142857142857143,
  0.9733245149911817),
 ('Travel_Rarely',
  ('1_companies',),
  259,
  0.29331823329558326,
  0.7640117994100295,
  1.0410839797516298),
 ('Travel_Rarely',
  ('1_companies', '3_WLBalance'),
  173,
  0.19592298980747452,
  0.7792792792792793,
  1.061888277166055),
 ('Travel_Rarely',
  ('1_companies', 'No'),
  231,
  0.26160815402038506,
  0.7598684210526315,
  1.0354379873294346),
 ('Travel_Rarely',
  ('1_stockOption',),
  248,
  0.2808607021517554,
  0.7209302325581395,
  0.9823786965259833),
 ('Travel_Rarely',
  ('1_stockOption', 'No'),
  235,
  0.26613816534541335,
  0.7230769230769231,
  0.9853038936372269),
 ('Travel_Rarely',
  ('2.0_Time',),
  310,
  0.3510758776896942,
  0.7328605200945626,
  0.9986355543881155),
 ('Travel_Rarely',
  ('2.0_Time', '3_JIvol'),
  174,
  0.1970554926387316,
  0.710204081632653,
  0.9677626606198034),
 ('Travel_Rarely',
  ('2.0_Time', '3_WLBalance'),
  178,
  0.2015855039637599,
  0.7574468085106383,
  1.0321381665353297),
 ('Travel_Rarely',
  ('2.0_Time', 'Male'),
  200,
  0.22650056625141562,
  0.7352941176470589,
  1.0019517066085692),
 ('Travel_Rarely',
  ('2.0_Time', 'Male', 'No'),
  179,
  0.20271800679501698,
  0.7366255144032922,
  1.0037659401513996),
 ('Travel_Rarely',
  ('2.0_Time', 'No'),
  275,
  0.3114382785956965,
  0.7294429708222812,
  0.9939786161050529),
 ('Travel_Rarely',
  ('2_YearsInCurrentRole',),
  179,
  0.20271800679501698,
  0.7336065573770492,
  0.9996521453147136),
 ('Travel_Rarely',
  ('3.0_Time',),
  180,
  0.20385050962627407,
  0.728744939271255,
  0.9930274403958614),
 ('Travel_Rarely',
  ('3.0_Time', 'No'),
  165,
  0.1868629671574179,
  0.7236842105263158,
  0.9861314165042235),
 ('Travel_Rarely',
  ('3_JIvol',),
  367,
  0.41562853907134767,
  0.716796875,
  0.9767463589891975),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance'),
  231,
  0.26160815402038506,
  0.7451612903225806,
  1.0153972520908006),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance', 'No'),
  215,
  0.2434881087202718,
  0.7413793103448276,
  1.0102437207322266),
 ('Travel_Rarely',
  ('3_JIvol', 'Male'),
  225,
  0.2548131370328426,
  0.7009345794392523,
  0.9551315334025614),
 ('Travel_Rarely',
  ('3_JIvol', 'No'),
  336,
  0.38052095130237823,
  0.7103594080338267,
  0.9679743168115261),
 ('Travel_Rarely',
  ('3_JSat',),
  211,
  0.23895809739524349,
  0.7644927536231884,
  1.041739354088388),
 ('Travel_Rarely',
  ('3_JSat', 'No'),
  189,
  0.21404303510758776,
  0.7590361445783133,
  1.0343038821954484),
 ('Travel_Rarely',
  ('3_RSat',),
  208,
  0.23556058890147225,
  0.7536231884057971,
  1.0269278940776525),
 ('Travel_Rarely',
  ('3_RSat', 'No'),
  189,
  0.21404303510758776,
  0.7470355731225297,
  1.0179512516469038),
 ('Travel_Rarely',
  ('3_WLBalance',),
  405,
  0.45866364665911663,
  0.7570093457943925,
  1.0315420560747663),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male'),
  240,
  0.2718006795016987,
  0.7453416149068323,
  1.0156429721647113),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male', 'No'),
  221,
  0.25028312570781425,
  0.7542662116040956,
  1.0278041124173092),
 ('Travel_Rarely',
  ('3_WLBalance', 'No'),
  369,
  0.4178935447338618,
  0.7561475409836066,
  1.030367714025501),
 ('Travel_Rarely',
  ('4_ESat',),
  195,
  0.22083805209513024,
  0.7677165354330708,
  1.0461322543015457),
 ('Travel_Rarely',
  ('4_ESat', 'No'),
  177,
  0.20045300113250283,
  0.7662337662337663,
  1.0441117524450858),
 ('Travel_Rarely',
  ('4_RSat',),
  189,
  0.21404303510758776,
  0.7269230769230769,
  0.9905448717948718),
 ('Travel_Rarely',
  ('4_RSat', 'No'),
  170,
  0.19252548131370328,
  0.7172995780590717,
  0.9774313694848153),
 ('Travel_Rarely',
  ('Bachelor',),
  280,
  0.3171007927519819,
  0.7799442896935933,
  1.0627944564806218),
 ('Travel_Rarely',
  ('Bachelor', 'Male'),
  171,
  0.19365798414496035,
  0.7702702702702703,
  1.049612112112112),
 ('Travel_Rarely',
  ('Bachelor', 'No'),
  250,
  0.28312570781426954,
  0.778816199376947,
  1.0612572593361793),
 ('Travel_Rarely',
  ('EntryLevel',),
  265,
  0.3001132502831257,
  0.728021978021978,
  0.9920422941256275),
 ('Travel_Rarely',
  ('EntryLevel', 'No'),
  221,
  0.25028312570781425,
  0.7175324675324676,
  0.9777487173320507),
 ('Travel_Rarely',
  ('Female',),
  254,
  0.2876557191392978,
  0.7405247813411079,
  1.0090792930928985),
 ('Travel_Rarely',
  ('Female', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('Male',),
  394,
  0.44620611551528877,
  0.7296296296296296,
  0.9942329675354367),
 ('Travel_Rarely',
  ('Male', 'No'),
  359,
  0.40656851642129105,
  0.7311608961303462,
  0.9963195544492218),
 ('Travel_Rarely',
  ('MidLevel',),
  237,
  0.26840317100792754,
  0.7292307692307692,
  0.9936894586894587),
 ('Travel_Rarely',
  ('MidLevel', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('No',),
  588,
  0.665911664779162,
  0.7322540473225405,
  0.9978091416447581),
 ('Travel_Rarely',
  ('Yes',),
  234,
  0.2650056625141563,
  0.7358490566037735,
  1.0027078965758212),
 ('Travel_Rarely',
  ('Yes', 'No'),
  174,
  0.1970554926387316,
  0.7310924369747899,
  0.9962262682850919),
 ('Travel_Rarely',
  ('[1009.0, 3607.8)_Income',),
  205,
  0.232163080407701,
  0.7321428571428571,
  0.9976576278659612),
 ('Travel_Rarely',
  ('[1009.0, 3607.8)_Income', 'No'),
  189,
  0.21404303510758776,
  0.7241379310344828,
  0.986749680715198),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%',),
  268,
  0.3035107587768969,
  0.7342465753424657,
  1.0005242685607982),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'Male'),
  176,
  0.19932049830124576,
  0.7457627118644068,
  1.0162167817535048),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'No'),
  240,
  0.2718006795016987,
  0.729483282674772,
  0.9940335472250366),
 ('Travel_Rarely',
  ('[13.8, 16.6)_%',),
  170,
  0.19252548131370328,
  0.74235807860262,
  1.011577443527953),
 ('Travel_Rarely',
  ('[25.0, 32.0)_Age',),
  161,
  0.1823329558323896,
  0.7219730941704036,
  0.9837997564081271),
 ('Travel_Rarely',
  ('[32.0, 39.0)_Age',),
  224,
  0.2536806342015855,
  0.7156549520766773,
  0.975190312783497),
 ('Travel_Rarely',
  ('[32.0, 39.0)_Age', 'No'),
  207,
  0.23442808607021517,
  0.71875,
  0.9794077932098766)}

In [49]:
rules2 = apriori(baskets, supp=25, zmin=2, target='r', conf=80, 
                report='ascl') 
print('Number of rule:', len(rules2))
set(rules2)

Number of rule: 56

{('No',
  ('0_stockOption',),
  336,
  0.38052095130237823,
  0.8682170542635659,
  0.954714394663423),
 ('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies',),
  304,
  0.34428086070215175,
  0.8967551622418879,
  0.986095651630868),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption',),
  325,
  0.36806342015855037,
  0.9447674418604651,
  1.0388912218714703),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time',),
  377,
  0.4269535673839185,
  0.8912529550827423,
  0.9800452793749209),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('2_YearsInCurrentRole',),
  219,
  0.2480181200453001,
  0.8975409836065574,
  0.9869597615499255),
 ('No',
  ('3.0_Time',),
  228,
  0.2582106455266138,
  0.9230769230769231,
  1.0150397547657821),
 ('No',
  ('3_ESat',),
  253,
  0.2865232163080408,
  0.9267399267399268,
  1.019067690300567),
 ('No', ('3_JIvol',), 473, 0.535673839184598, 0.923828125, 1.0158657962328768),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_JSat',),
  249,
  0.28199320498301245,
  0.9021739130434783,
  0.9920542530727164),
 ('No',
  ('3_RSat',),
  253,
  0.2865232163080408,
  0.9166666666666666,
  1.0079908675799087),
 ('No',
  ('3_WLBalance',),
  488,
  0.5526613816534541,
  0.9121495327102803,
  1.0030237078246296),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('4_ESat',),
  231,
  0.26160815402038506,
  0.9094488188976378,
  1.0000539316147126),
 ('No',
  ('4_JSat',),
  243,
  0.27519818799546997,
  0.9418604651162791,
  1.0356946334964812),
 ('No',
  ('4_RSat',),
  237,
  0.26840317100792754,
  0.9115384615384615,
  1.0023517578312098),
 ('No',
  ('Bachelor',),
  321,
  0.3635334088335221,
  0.8941504178272981,
  0.9832314059047375),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel',),
  308,
  0.3488108720271801,
  0.8461538461538461,
  0.9304531085353003),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female',),
  312,
  0.35334088335220837,
  0.9096209912536443,
  1.000243256882899),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male',),
  491,
  0.5560588901472253,
  0.9092592592592592,
  0.9998454868317882),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('Master',),
  209,
  0.23669309173272934,
  0.9330357142857143,
  1.0259907045009784),
 ('No', ('MidLevel',), 312, 0.35334088335220837, 0.96, 1.0556413449564135),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Travel_Rarely',),
  588,
  0.665911664779162,
  0.9074074074074074,
  0.9978091416447581),
 ('No',
  ('[1.0, 3.8)_Distance',),
  287,
  0.3250283125707814,
  0.9228295819935691,
  1.014767771980475),
 ('No',
  ('[1009.0, 3607.8)_Income',),
  261,
  0.2955832389580974,
  0.9321428571428572,
  1.0250088952143748),
 ('No',
  ('[11.0, 13.8)_%',),
  329,
  0.3725934314835787,
  0.9013698630136986,
  0.9911700984322489),
 ('No',
  ('[11.0, 13.8)_%', 'Male'),
  212,
  0.24009060022650056,
  0.8983050847457628,
  0.987799987335627),
 ('No',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8955223880597015,
  0.9847400605936693),
 ('No',
  ('[13.8, 16.6)_%',),
  209,
  0.23669309173272934,
  0.9126637554585153,
  1.0035891607345815),
 ('No',
  ('[25.0, 32.0)_Age',),
  200,
  0.22650056625141562,
  0.8968609865470852,
  0.9862120188307301),
 ('No',
  ('[32.0, 39.0)_Age',),
  288,
  0.3261608154020385,
  0.9201277955271565,
  1.0117968162521536),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403),
 ('No',
  ('[3607.8, 6206.6)_Income',),
  244,
  0.27633069082672707,
  0.9207547169811321,
  1.0124861956342959)}

In [50]:
rules3 = apriori(baskets, supp=25, zmin=2, target='r', conf=90, 
                report='ascl') 
print('Number of rule:', len(rules3))
set(rules3)

Number of rule: 37

{('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_stockOption',),
  325,
  0.36806342015855037,
  0.9447674418604651,
  1.0388912218714703),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('3.0_Time',),
  228,
  0.2582106455266138,
  0.9230769230769231,
  1.0150397547657821),
 ('No',
  ('3_ESat',),
  253,
  0.2865232163080408,
  0.9267399267399268,
  1.019067690300567),
 ('No', ('3_JIvol',), 473, 0.535673839184598, 0.923828125, 1.0158657962328768),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_JSat',),
  249,
  0.28199320498301245,
  0.9021739130434783,
  0.9920542530727164),
 ('No',
  ('3_RSat',),
  253,
  0.2865232163080408,
  0.9166666666666666,
  1.0079908675799087),
 ('No',
  ('3_WLBalance',),
  488,
  0.5526613816534541,
  0.9121495327102803,
  1.0030237078246296),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('4_ESat',),
  231,
  0.26160815402038506,
  0.9094488188976378,
  1.0000539316147126),
 ('No',
  ('4_JSat',),
  243,
  0.27519818799546997,
  0.9418604651162791,
  1.0356946334964812),
 ('No',
  ('4_RSat',),
  237,
  0.26840317100792754,
  0.9115384615384615,
  1.0023517578312098),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Female',),
  312,
  0.35334088335220837,
  0.9096209912536443,
  1.000243256882899),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male',),
  491,
  0.5560588901472253,
  0.9092592592592592,
  0.9998454868317882),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('Master',),
  209,
  0.23669309173272934,
  0.9330357142857143,
  1.0259907045009784),
 ('No', ('MidLevel',), 312, 0.35334088335220837, 0.96, 1.0556413449564135),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Travel_Rarely',),
  588,
  0.665911664779162,
  0.9074074074074074,
  0.9978091416447581),
 ('No',
  ('[1.0, 3.8)_Distance',),
  287,
  0.3250283125707814,
  0.9228295819935691,
  1.014767771980475),
 ('No',
  ('[1009.0, 3607.8)_Income',),
  261,
  0.2955832389580974,
  0.9321428571428572,
  1.0250088952143748),
 ('No',
  ('[11.0, 13.8)_%',),
  329,
  0.3725934314835787,
  0.9013698630136986,
  0.9911700984322489),
 ('No',
  ('[13.8, 16.6)_%',),
  209,
  0.23669309173272934,
  0.9126637554585153,
  1.0035891607345815),
 ('No',
  ('[32.0, 39.0)_Age',),
  288,
  0.3261608154020385,
  0.9201277955271565,
  1.0117968162521536),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403),
 ('No',
  ('[3607.8, 6206.6)_Income',),
  244,
  0.27633069082672707,
  0.9207547169811321,
  1.0124861956342959)}

In [51]:
print('Numeber of rules with support = 25 e zmin = 2')

print('Number of rules, confidance [60]:', len(rules))
print('Number of rules, confidance [70]:', len(rules1))
print('Number of rules, confidance [80]:', len(rules2))
print('Number of rules, confidance [90]:', len(rules3))

Numeber of rules with support = 25 e zmin = 2
Number of rules, confidance [60]: 258
Number of rules, confidance [70]: 117
Number of rules, confidance [80]: 56
Number of rules, confidance [90]: 37

# Association Rules zmin = 3

In [52]:
rules = apriori(baskets, supp=25, zmin=3, target='r', conf=60, 
                report='ascl') 
print('Number of rule:', len(rules))
set(rules)

Number of rule: 155

{('3_JIvol',
  ('1_stockOption', 'No'),
  197,
  0.22310305775764439,
  0.6061538461538462,
  1.0453786057692307),
 ('3_JIvol',
  ('3_JSat', 'No'),
  152,
  0.17214043035107587,
  0.6104417670682731,
  1.05277359437751),
 ('3_JIvol',
  ('3_RSat', 'No'),
  155,
  0.1755379388448471,
  0.6126482213438735,
  1.0565788661067195),
 ('3_JIvol',
  ('3_WLBalance', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6143344709897611,
  1.0594869880546076),
 ('3_JIvol',
  ('4_ESat', 'No'),
  141,
  0.159682899207248,
  0.6103896103896104,
  1.0526836444805194),
 ('3_JIvol',
  ('4_JSat', 'No'),
  149,
  0.16874292185730463,
  0.6131687242798354,
  1.0574765303497942),
 ('3_JIvol',
  ('Male', 'No'),
  298,
  0.33748584371460927,
  0.6069246435845214,
  1.0467079302443991),
 ('3_JIvol',
  ('[3607.8, 6206.6)_Income', 'No'),
  149,
  0.16874292185730463,
  0.610655737704918,
  1.0531426101434427),
 ('3_WLBalance',
  ('0_stockOption', '3_JIvol'),
  141,
  0.159682899207248,
  0.6351351351351351,
  1.048269765092195),
 ('3_WLBalance',
  ('0_stockOption', 'Male'),
  151,
  0.1710079275198188,
  0.604,
  0.9968822429906542),
 ('3_WLBalance',
  ('0_stockOption', 'No'),
  211,
  0.23895809739524349,
  0.6279761904761905,
  1.0364541611036937),
 ('3_WLBalance',
  ('0_stockOption', 'Travel_Rarely'),
  176,
  0.19932049830124576,
  0.6308243727598566,
  1.0411549927980437),
 ('3_WLBalance',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  154,
  0.17440543601359004,
  0.6416666666666667,
  1.0590498442367602),
 ('3_WLBalance',
  ('1_companies', 'No'),
  201,
  0.2276330690826727,
  0.6611842105263158,
  1.0912629119527792),
 ('3_WLBalance',
  ('1_companies', 'Travel_Rarely'),
  173,
  0.19592298980747452,
  0.667953667953668,
  1.1024356800057735),
 ('3_WLBalance',
  ('1_companies', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.670995670995671,
  1.107456406521827),
 ('3_WLBalance',
  ('1_stockOption', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6008064516129032,
  0.9916113958396141),
 ('3_WLBalance',
  ('1_stockOption', 'Travel_Rarely', 'No'),
  142,
  0.16081540203850508,
  0.6042553191489362,
  0.9973036388944124),
 ('3_WLBalance',
  ('3.0_Time', 'No'),
  148,
  0.16761041902604756,
  0.6491228070175439,
  1.0713559599934415),
 ('3_WLBalance',
  ('3_ESat', 'No'),
  153,
  0.17327293318233294,
  0.6047430830039525,
  0.9981086771822245),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6040268456375839,
  0.996926550837358),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6177777777777778,
  1.0196220145379025),
 ('3_WLBalance',
  ('3_JIvol', 'No'),
  290,
  0.32842582106455265,
  0.6131078224101479,
  1.011914405959179),
 ('3_WLBalance',
  ('3_JIvol', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.6294277929155313,
  1.0388499834475031),
 ('3_WLBalance',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  215,
  0.2434881087202718,
  0.6398809523809523,
  1.0561025812194036),
 ('3_WLBalance',
  ('3_JSat', 'No'),
  156,
  0.17667044167610418,
  0.6265060240963856,
  1.0340276995833801),
 ('3_WLBalance',
  ('3_RSat', 'No'),
  155,
  0.1755379388448471,
  0.6126482213438735,
  1.0111558494329727),
 ('3_WLBalance',
  ('4_ESat', 'No'),
  147,
  0.1664779161947905,
  0.6363636363636364,
  1.0502973661852166),
 ('3_WLBalance',
  ('4_RSat', 'No'),
  152,
  0.17214043035107587,
  0.6413502109704642,
  1.0585275444615323),
 ('3_WLBalance',
  ('Bachelor', 'No'),
  193,
  0.21857304643261607,
  0.6012461059190031,
  0.9923370308906163),
 ('3_WLBalance',
  ('Bachelor', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.6214285714285714,
  1.0256475300400534),
 ('3_WLBalance',
  ('Bachelor', 'Travel_Rarely', 'No'),
  157,
  0.17780294450736125,
  0.628,
  1.0364934579439253),
 ('3_WLBalance',
  ('EntryLevel', 'No'),
  187,
  0.21177802944507362,
  0.6071428571428571,
  1.0020694259012015),
 ('3_WLBalance',
  ('EntryLevel', 'Travel_Rarely', 'No'),
  133,
  0.1506228765571914,
  0.6018099547511312,
  0.9932676449443905),
 ('3_WLBalance',
  ('Female', 'No'),
  195,
  0.22083805209513024,
  0.625,
  1.0315420560747663),
 ('3_WLBalance',
  ('Female', 'Travel_Rarely'),
  165,
  0.1868629671574179,
  0.6496062992125984,
  1.072153948046214),
 ('3_WLBalance',
  ('Female', 'Travel_Rarely', 'No'),
  148,
  0.16761041902604756,
  0.6462882096069869,
  1.0666775496877934),
 ('3_WLBalance',
  ('Male', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.6091370558375635,
  1.005360785616016),
 ('3_WLBalance',
  ('Male', 'Travel_Rarely', 'No'),
  221,
  0.25028312570781425,
  0.6155988857938719,
  1.0160258245906333),
 ('3_WLBalance',
  ('MidLevel', 'No'),
  188,
  0.2129105322763307,
  0.6025641025641025,
  0.9945123412413132),
 ('3_WLBalance',
  ('MidLevel', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0376355534524233),
 ('3_WLBalance',
  ('MidLevel', 'Travel_Rarely', 'No'),
  143,
  0.16194790486976218,
  0.6244541484716157,
  1.0306411459821245),
 ('3_WLBalance',
  ('Travel_Rarely', 'No'),
  369,
  0.4178935447338618,
  0.6275510204081632,
  1.0357524318138471),
 ('3_WLBalance',
  ('Yes', 'No'),
  143,
  0.16194790486976218,
  0.6008403361344538,
  0.9916673211340611),
 ('3_WLBalance',
  ('Yes', 'Travel_Rarely'),
  142,
  0.16081540203850508,
  0.6068376068376068,
  1.001565620257209),
 ('3_WLBalance',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  161,
  0.1823329558323896,
  0.6007462686567164,
  0.9915120658390292),
 ('3_WLBalance',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  137,
  0.1551528878822197,
  0.6116071428571429,
  1.0094375834445928),
 ('Male',
  ('0_stockOption', '3_JIvol'),
  147,
  0.1664779161947905,
  0.6621621621621622,
  1.0827577577577578),
 ('Male',
  ('0_stockOption', '3_WLBalance'),
  151,
  0.1710079275198188,
  0.634453781512605,
  1.0374494242141301),
 ('Male',
  ('0_stockOption', 'No'),
  218,
  0.24688561721404303,
  0.6488095238095238,
  1.060923721340388),
 ('Male',
  ('0_stockOption', 'Travel_Rarely'),
  181,
  0.20498301245753114,
  0.6487455197132617,
  1.0608190627903888),
 ('Male',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  156,
  0.17667044167610418,
  0.65,
  1.0628703703703704),
 ('Male',
  ('1_companies', '3_WLBalance'),
  140,
  0.15855039637599094,
  0.6306306306306306,
  1.0311978645311979),
 ('Male',
  ('1_companies', 'No'),
  191,
  0.21630804077010193,
  0.6282894736842105,
  1.0273696393762184),
 ('Male',
  ('1_companies', 'Travel_Rarely'),
  162,
  0.18346545866364666,
  0.6254826254826255,
  1.0227799227799228),
 ('Male',
  ('1_companies', 'Travel_Rarely', 'No'),
  145,
  0.16421291053227632,
  0.6277056277056277,
  1.0264149430816099),
 ('Male',
  ('2.0_Time', '3_JIvol'),
  156,
  0.17667044167610418,
  0.636734693877551,
  1.0411791383219955),
 ('Male',
  ('2.0_Time', '3_JIvol', 'No'),
  142,
  0.16081540203850508,
  0.6339285714285714,
  1.0365906084656085),
 ('Male',
  ('2.0_Time', '3_WLBalance'),
  155,
  0.1755379388448471,
  0.6595744680851063,
  1.0785263987391647),
 ('Male',
  ('2.0_Time', 'No'),
  243,
  0.27519818799546997,
  0.6445623342175066,
  1.0539787798408489),
 ('Male',
  ('2.0_Time', 'Travel_Rarely'),
  200,
  0.22650056625141562,
  0.6451612903225806,
  1.054958183990442),
 ('Male',
  ('2.0_Time', 'Travel_Rarely', 'No'),
  179,
  0.20271800679501698,
  0.6509090909090909,
  1.0643569023569024),
 ('Male',
  ('3_ESat', 'No'),
  157,
  0.17780294450736125,
  0.6205533596837944,
  1.0147196603718343),
 ('Male',
  ('3_JIvol', '3_WLBalance'),
  192,
  0.217440543601359,
  0.6193548387096774,
  1.0127598566308245),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'No'),
  180,
  0.20385050962627407,
  0.6206896551724138,
  1.0149425287356322),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6017316017316018,
  0.9839426006092673),
 ('Male',
  ('3_JIvol', 'No'),
  298,
  0.33748584371460927,
  0.6300211416490487,
  1.0302012371779814),
 ('Male',
  ('3_JIvol', 'Travel_Rarely'),
  225,
  0.2548131370328426,
  0.6130790190735694,
  1.0024977293369663),
 ('Male',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  207,
  0.23442808607021517,
  0.6160714285714286,
  1.007390873015873),
 ('Male',
  ('3_RSat', 'No'),
  157,
  0.17780294450736125,
  0.6205533596837944,
  1.0147196603718343),
 ('Male',
  ('3_WLBalance', 'No'),
  293,
  0.3318233295583239,
  0.6004098360655737,
  0.981781268973892),
 ('Male',
  ('4_RSat', 'No'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0280278168463823),
 ('Male',
  ('Bachelor', 'No'),
  200,
  0.22650056625141562,
  0.6230529595015576,
  1.0188069689627322),
 ('Male',
  ('Bachelor', 'Travel_Rarely'),
  171,
  0.19365798414496035,
  0.6107142857142858,
  0.9986309523809523),
 ('Male',
  ('Bachelor', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.62,
  1.0138148148148147),
 ('Male',
  ('MidLevel', 'No'),
  192,
  0.217440543601359,
  0.6153846153846154,
  1.0062678062678063),
 ('Male',
  ('MidLevel', 'Travel_Rarely'),
  149,
  0.16874292185730463,
  0.6286919831223629,
  1.0280278168463823),
 ('Male',
  ('MidLevel', 'Travel_Rarely', 'No'),
  144,
  0.16308040770101925,
  0.62882096069869,
  1.0282387190684135),
 ('Male',
  ('Travel_Rarely', 'No'),
  359,
  0.40656851642129105,
  0.6105442176870748,
  0.9983528596623835),
 ('Male',
  ('Yes', 'No'),
  145,
  0.16421291053227632,
  0.6092436974789915,
  0.9962262682850919),
 ('Male',
  ('[1.0, 3.8)_Distance', 'No'),
  175,
  0.19818799546998866,
  0.6097560975609756,
  0.9970641373080398),
 ('Male',
  ('[1009.0, 3607.8)_Income', 'No'),
  175,
  0.19818799546998866,
  0.6704980842911877,
  1.0963885341279977),
 ('Male',
  ('[11.0, 13.8)_%', 'No'),
  212,
  0.24009060022650056,
  0.6443768996960486,
  1.0536755600585388),
 ('Male',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  176,
  0.19932049830124576,
  0.6567164179104478,
  1.073852957435047),
 ('Male',
  ('[11.0, 13.8)_%', 'Travel_Rarely', 'No'),
  158,
  0.17893544733861835,
  0.6583333333333333,
  1.076496913580247),
 ('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Yes', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.7435897435897436,
  0.8176709135613245),
 ('No',
  ('[11.0, 13.8)_%', 'Male'),
  212,
  0.24009060022650056,
  0.8983050847457628,
  0.987799987335627),
 ('No',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8955223880597015,
  0.9847400605936693),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403),
 ('Travel_Rarely',
  ('0_stockOption', '3_JIvol'),
  159,
  0.18006795016987542,
  0.7162162162162162,
  0.9759551217884551),
 ('Travel_Rarely',
  ('0_stockOption', '3_WLBalance'),
  176,
  0.19932049830124576,
  0.7394957983193278,
  1.007677144932047),
 ('Travel_Rarely',
  ('0_stockOption', 'Male'),
  181,
  0.20498301245753114,
  0.724,
  0.9865617283950617),
 ('Travel_Rarely',
  ('0_stockOption', 'No'),
  240,
  0.2718006795016987,
  0.7142857142857143,
  0.9733245149911817),
 ('Travel_Rarely',
  ('1_companies', '3_WLBalance'),
  173,
  0.19592298980747452,
  0.7792792792792793,
  1.061888277166055),
 ('Travel_Rarely',
  ('1_companies', 'No'),
  231,
  0.26160815402038506,
  0.7598684210526315,
  1.0354379873294346),
 ('Travel_Rarely',
  ('1_stockOption', 'No'),
  235,
  0.26613816534541335,
  0.7230769230769231,
  0.9853038936372269),
 ('Travel_Rarely',
  ('2.0_Time', '3_JIvol'),
  174,
  0.1970554926387316,
  0.710204081632653,
  0.9677626606198034),
 ('Travel_Rarely',
  ('2.0_Time', '3_JIvol', 'No'),
  156,
  0.17667044167610418,
  0.6964285714285714,
  0.9489914021164021),
 ('Travel_Rarely',
  ('2.0_Time', '3_WLBalance'),
  178,
  0.2015855039637599,
  0.7574468085106383,
  1.0321381665353297),
 ('Travel_Rarely',
  ('2.0_Time', 'Male'),
  200,
  0.22650056625141562,
  0.7352941176470589,
  1.0019517066085692),
 ('Travel_Rarely',
  ('2.0_Time', 'Male', 'No'),
  179,
  0.20271800679501698,
  0.7366255144032922,
  1.0037659401513996),
 ('Travel_Rarely',
  ('2.0_Time', 'No'),
  275,
  0.3114382785956965,
  0.7294429708222812,
  0.9939786161050529),
 ('Travel_Rarely',
  ('3.0_Time', 'No'),
  165,
  0.1868629671574179,
  0.7236842105263158,
  0.9861314165042235),
 ('Travel_Rarely',
  ('3_ESat', 'No'),
  173,
  0.19592298980747452,
  0.6837944664031621,
  0.9317754843117162),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance'),
  231,
  0.26160815402038506,
  0.7451612903225806,
  1.0153972520908006),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance', 'No'),
  215,
  0.2434881087202718,
  0.7413793103448276,
  1.0102437207322266),
 ('Travel_Rarely',
  ('3_JIvol', 'Male'),
  225,
  0.2548131370328426,
  0.7009345794392523,
  0.9551315334025614),
 ('Travel_Rarely',
  ('3_JIvol', 'Male', 'No'),
  207,
  0.23442808607021517,
  0.6946308724832215,
  0.946541759880686),
 ('Travel_Rarely',
  ('3_JIvol', 'No'),
  336,
  0.38052095130237823,
  0.7103594080338267,
  0.9679743168115261),
 ('Travel_Rarely',
  ('3_JSat', 'No'),
  189,
  0.21404303510758776,
  0.7590361445783133,
  1.0343038821954484),
 ('Travel_Rarely',
  ('3_RSat', 'No'),
  189,
  0.21404303510758776,
  0.7470355731225297,
  1.0179512516469038),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male'),
  240,
  0.2718006795016987,
  0.7453416149068323,
  1.0156429721647113),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male', 'No'),
  221,
  0.25028312570781425,
  0.7542662116040956,
  1.0278041124173092),
 ('Travel_Rarely',
  ('3_WLBalance', 'No'),
  369,
  0.4178935447338618,
  0.7561475409836066,
  1.030367714025501),
 ('Travel_Rarely',
  ('4_ESat', 'No'),
  177,
  0.20045300113250283,
  0.7662337662337663,
  1.0441117524450858),
 ('Travel_Rarely',
  ('4_JSat', 'No'),
  168,
  0.19026047565118911,
  0.691358024691358,
  0.9420819996951684),
 ('Travel_Rarely',
  ('4_RSat', 'No'),
  170,
  0.19252548131370328,
  0.7172995780590717,
  0.9774313694848153),
 ('Travel_Rarely',
  ('Bachelor', 'Male'),
  171,
  0.19365798414496035,
  0.7702702702702703,
  1.049612112112112),
 ('Travel_Rarely',
  ('Bachelor', 'No'),
  250,
  0.28312570781426954,
  0.778816199376947,
  1.0612572593361793),
 ('Travel_Rarely',
  ('EntryLevel', 'No'),
  221,
  0.25028312570781425,
  0.7175324675324676,
  0.9777487173320507),
 ('Travel_Rarely',
  ('Female', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('Male', 'No'),
  359,
  0.40656851642129105,
  0.7311608961303462,
  0.9963195544492218),
 ('Travel_Rarely',
  ('MidLevel', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('Yes', 'No'),
  174,
  0.1970554926387316,
  0.7310924369747899,
  0.9962262682850919),
 ('Travel_Rarely',
  ('[1.0, 3.8)_Distance', 'No'),
  196,
  0.22197055492638731,
  0.6829268292682927,
  0.9305931948208371),
 ('Travel_Rarely',
  ('[1009.0, 3607.8)_Income', 'No'),
  189,
  0.21404303510758776,
  0.7241379310344828,
  0.986749680715198),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'Male'),
  176,
  0.19932049830124576,
  0.7457627118644068,
  1.0162167817535048),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'No'),
  240,
  0.2718006795016987,
  0.729483282674772,
  0.9940335472250366),
 ('Travel_Rarely',
  ('[32.0, 39.0)_Age', 'No'),
  207,
  0.23442808607021517,
  0.71875,
  0.9794077932098766),
 ('Travel_Rarely',
  ('[3607.8, 6206.6)_Income', 'No'),
  170,
  0.19252548131370328,
  0.6967213114754098,
  0.9493903056061526)}

In [53]:
rules1 = apriori(baskets, supp=25, zmin=3, target='r', conf=70, 
                report='ascl') 
print('Number of rule:', len(rules1))
set(rules1)

Number of rule: 64

{('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('Yes', 'Travel_Rarely'),
  174,
  0.1970554926387316,
  0.7435897435897436,
  0.8176709135613245),
 ('No',
  ('[11.0, 13.8)_%', 'Male'),
  212,
  0.24009060022650056,
  0.8983050847457628,
  0.987799987335627),
 ('No',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8955223880597015,
  0.9847400605936693),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403),
 ('Travel_Rarely',
  ('0_stockOption', '3_JIvol'),
  159,
  0.18006795016987542,
  0.7162162162162162,
  0.9759551217884551),
 ('Travel_Rarely',
  ('0_stockOption', '3_WLBalance'),
  176,
  0.19932049830124576,
  0.7394957983193278,
  1.007677144932047),
 ('Travel_Rarely',
  ('0_stockOption', 'Male'),
  181,
  0.20498301245753114,
  0.724,
  0.9865617283950617),
 ('Travel_Rarely',
  ('0_stockOption', 'No'),
  240,
  0.2718006795016987,
  0.7142857142857143,
  0.9733245149911817),
 ('Travel_Rarely',
  ('1_companies', '3_WLBalance'),
  173,
  0.19592298980747452,
  0.7792792792792793,
  1.061888277166055),
 ('Travel_Rarely',
  ('1_companies', 'No'),
  231,
  0.26160815402038506,
  0.7598684210526315,
  1.0354379873294346),
 ('Travel_Rarely',
  ('1_stockOption', 'No'),
  235,
  0.26613816534541335,
  0.7230769230769231,
  0.9853038936372269),
 ('Travel_Rarely',
  ('2.0_Time', '3_JIvol'),
  174,
  0.1970554926387316,
  0.710204081632653,
  0.9677626606198034),
 ('Travel_Rarely',
  ('2.0_Time', '3_WLBalance'),
  178,
  0.2015855039637599,
  0.7574468085106383,
  1.0321381665353297),
 ('Travel_Rarely',
  ('2.0_Time', 'Male'),
  200,
  0.22650056625141562,
  0.7352941176470589,
  1.0019517066085692),
 ('Travel_Rarely',
  ('2.0_Time', 'Male', 'No'),
  179,
  0.20271800679501698,
  0.7366255144032922,
  1.0037659401513996),
 ('Travel_Rarely',
  ('2.0_Time', 'No'),
  275,
  0.3114382785956965,
  0.7294429708222812,
  0.9939786161050529),
 ('Travel_Rarely',
  ('3.0_Time', 'No'),
  165,
  0.1868629671574179,
  0.7236842105263158,
  0.9861314165042235),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance'),
  231,
  0.26160815402038506,
  0.7451612903225806,
  1.0153972520908006),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance', 'No'),
  215,
  0.2434881087202718,
  0.7413793103448276,
  1.0102437207322266),
 ('Travel_Rarely',
  ('3_JIvol', 'Male'),
  225,
  0.2548131370328426,
  0.7009345794392523,
  0.9551315334025614),
 ('Travel_Rarely',
  ('3_JIvol', 'No'),
  336,
  0.38052095130237823,
  0.7103594080338267,
  0.9679743168115261),
 ('Travel_Rarely',
  ('3_JSat', 'No'),
  189,
  0.21404303510758776,
  0.7590361445783133,
  1.0343038821954484),
 ('Travel_Rarely',
  ('3_RSat', 'No'),
  189,
  0.21404303510758776,
  0.7470355731225297,
  1.0179512516469038),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male'),
  240,
  0.2718006795016987,
  0.7453416149068323,
  1.0156429721647113),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male', 'No'),
  221,
  0.25028312570781425,
  0.7542662116040956,
  1.0278041124173092),
 ('Travel_Rarely',
  ('3_WLBalance', 'No'),
  369,
  0.4178935447338618,
  0.7561475409836066,
  1.030367714025501),
 ('Travel_Rarely',
  ('4_ESat', 'No'),
  177,
  0.20045300113250283,
  0.7662337662337663,
  1.0441117524450858),
 ('Travel_Rarely',
  ('4_RSat', 'No'),
  170,
  0.19252548131370328,
  0.7172995780590717,
  0.9774313694848153),
 ('Travel_Rarely',
  ('Bachelor', 'Male'),
  171,
  0.19365798414496035,
  0.7702702702702703,
  1.049612112112112),
 ('Travel_Rarely',
  ('Bachelor', 'No'),
  250,
  0.28312570781426954,
  0.778816199376947,
  1.0612572593361793),
 ('Travel_Rarely',
  ('EntryLevel', 'No'),
  221,
  0.25028312570781425,
  0.7175324675324676,
  0.9777487173320507),
 ('Travel_Rarely',
  ('Female', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('Male', 'No'),
  359,
  0.40656851642129105,
  0.7311608961303462,
  0.9963195544492218),
 ('Travel_Rarely',
  ('MidLevel', 'No'),
  229,
  0.25934314835787087,
  0.7339743589743589,
  1.000153331750554),
 ('Travel_Rarely',
  ('Yes', 'No'),
  174,
  0.1970554926387316,
  0.7310924369747899,
  0.9962262682850919),
 ('Travel_Rarely',
  ('[1009.0, 3607.8)_Income', 'No'),
  189,
  0.21404303510758776,
  0.7241379310344828,
  0.986749680715198),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'Male'),
  176,
  0.19932049830124576,
  0.7457627118644068,
  1.0162167817535048),
 ('Travel_Rarely',
  ('[11.0, 13.8)_%', 'No'),
  240,
  0.2718006795016987,
  0.729483282674772,
  0.9940335472250366),
 ('Travel_Rarely',
  ('[32.0, 39.0)_Age', 'No'),
  207,
  0.23442808607021517,
  0.71875,
  0.9794077932098766)}

In [54]:
rules2 = apriori(baskets, supp=25, zmin=3, target='r', conf=80, 
                report='ascl') 
print('Number of rule:', len(rules2))
set(rules2)

Number of rule: 28

{('No',
  ('0_stockOption', '3_JIvol'),
  198,
  0.22423556058890148,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('0_stockOption', '3_WLBalance'),
  211,
  0.23895809739524349,
  0.8865546218487395,
  0.9748788681101332),
 ('No',
  ('0_stockOption', 'Male'),
  218,
  0.24688561721404303,
  0.872,
  0.9588742216687423),
 ('No',
  ('0_stockOption', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8602150537634409,
  0.9459151836527002),
 ('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_companies', 'Travel_Rarely'),
  231,
  0.26160815402038506,
  0.8918918918918919,
  0.9807478711588301),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('2.0_Time', '3_WLBalance'),
  207,
  0.23442808607021517,
  0.8808510638297873,
  0.9686070851328794),
 ('No',
  ('2.0_Time', 'Male'),
  243,
  0.27519818799546997,
  0.8933823529411765,
  0.9823868214782799),
 ('No',
  ('2.0_Time', 'Travel_Rarely'),
  275,
  0.3114382785956965,
  0.8870967741935484,
  0.9754750331418471),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Bachelor', 'Travel_Rarely'),
  250,
  0.28312570781426954,
  0.8928571428571429,
  0.9818092866038072),
 ('No',
  ('EntryLevel', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.8339622641509434,
  0.9170469230949976),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('[11.0, 13.8)_%', 'Male'),
  212,
  0.24009060022650056,
  0.8983050847457628,
  0.987799987335627),
 ('No',
  ('[11.0, 13.8)_%', 'Travel_Rarely'),
  240,
  0.2718006795016987,
  0.8955223880597015,
  0.9847400605936693),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403)}

In [55]:
rules3 = apriori(baskets, supp=25, zmin=3, target='r', conf=90, 
                report='ascl') 
print('Number of rule:', len(rules3))
set(rules3)

Number of rule: 16

{('No',
  ('1_companies', '3_WLBalance'),
  201,
  0.2276330690826727,
  0.9054054054054054,
  0.9956076873885094),
 ('No',
  ('1_stockOption', 'Travel_Rarely'),
  235,
  0.26613816534541335,
  0.9475806451612904,
  1.0419846944924276),
 ('No',
  ('2.0_Time', '3_JIvol'),
  224,
  0.2536806342015855,
  0.9142857142857143,
  1.0053727094822986),
 ('No',
  ('3_JIvol', '3_WLBalance'),
  290,
  0.32842582106455265,
  0.9354838709677419,
  1.0286827622223116),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male'),
  298,
  0.33748584371460927,
  0.9283489096573209,
  1.0208369703952855),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_JIvol', 'Travel_Rarely'),
  336,
  0.38052095130237823,
  0.9155313351498637,
  1.006742427070149),
 ('No',
  ('3_WLBalance', 'Male'),
  293,
  0.3318233295583239,
  0.9099378881987578,
  1.0005917251301408),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('No',
  ('3_WLBalance', 'Travel_Rarely'),
  369,
  0.4178935447338618,
  0.9111111111111111,
  1.0018818320188183),
 ('No',
  ('Bachelor', 'Male'),
  200,
  0.22650056625141562,
  0.9009009009009009,
  0.9906544153119495),
 ('No',
  ('Female', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9015748031496063,
  0.9913954560163167),
 ('No',
  ('Male', 'Travel_Rarely'),
  359,
  0.40656851642129105,
  0.9111675126903553,
  1.001943852684413),
 ('No',
  ('MidLevel', 'Travel_Rarely'),
  229,
  0.25934314835787087,
  0.9662447257383966,
  1.0625082102453354),
 ('No',
  ('[32.0, 39.0)_Age', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.9241071428571429,
  1.0161726116349403)}

In [56]:
print('Numeber of rules with support = 25 e zmin = 3')

print('Number of rules, confidance [60]:', len(rules))
print('Number of rules, confidance [70]:', len(rules1))
print('Number of rules, confidance [80]:', len(rules2))
print('Number of rules, confidance [90]:', len(rules3))

Numeber of rules with support = 25 e zmin = 3
Number of rules, confidance [60]: 155
Number of rules, confidance [70]: 64
Number of rules, confidance [80]: 28
Number of rules, confidance [90]: 16

# Association Rules zmin = 4

In [57]:
rules = apriori(baskets, supp=25, zmin=4, target='r', conf=60, 
                report='ascl') 
print('Number of rule:', len(rules))
set(rules)

Number of rule: 30

{('3_JIvol',
  ('3_WLBalance', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6143344709897611,
  1.0594869880546076),
 ('3_WLBalance',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  154,
  0.17440543601359004,
  0.6416666666666667,
  1.0590498442367602),
 ('3_WLBalance',
  ('1_companies', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.670995670995671,
  1.107456406521827),
 ('3_WLBalance',
  ('1_stockOption', 'Travel_Rarely', 'No'),
  142,
  0.16081540203850508,
  0.6042553191489362,
  0.9973036388944124),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'No'),
  180,
  0.20385050962627407,
  0.6040268456375839,
  0.996926550837358),
 ('3_WLBalance',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6177777777777778,
  1.0196220145379025),
 ('3_WLBalance',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  215,
  0.2434881087202718,
  0.6398809523809523,
  1.0561025812194036),
 ('3_WLBalance',
  ('Bachelor', 'Travel_Rarely', 'No'),
  157,
  0.17780294450736125,
  0.628,
  1.0364934579439253),
 ('3_WLBalance',
  ('EntryLevel', 'Travel_Rarely', 'No'),
  133,
  0.1506228765571914,
  0.6018099547511312,
  0.9932676449443905),
 ('3_WLBalance',
  ('Female', 'Travel_Rarely', 'No'),
  148,
  0.16761041902604756,
  0.6462882096069869,
  1.0666775496877934),
 ('3_WLBalance',
  ('Male', 'Travel_Rarely', 'No'),
  221,
  0.25028312570781425,
  0.6155988857938719,
  1.0160258245906333),
 ('3_WLBalance',
  ('MidLevel', 'Travel_Rarely', 'No'),
  143,
  0.16194790486976218,
  0.6244541484716157,
  1.0306411459821245),
 ('Male',
  ('0_stockOption', 'Travel_Rarely', 'No'),
  156,
  0.17667044167610418,
  0.65,
  1.0628703703703704),
 ('Male',
  ('1_companies', 'Travel_Rarely', 'No'),
  145,
  0.16421291053227632,
  0.6277056277056277,
  1.0264149430816099),
 ('Male',
  ('2.0_Time', '3_JIvol', 'No'),
  142,
  0.16081540203850508,
  0.6339285714285714,
  1.0365906084656085),
 ('Male',
  ('2.0_Time', 'Travel_Rarely', 'No'),
  179,
  0.20271800679501698,
  0.6509090909090909,
  1.0643569023569024),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'No'),
  180,
  0.20385050962627407,
  0.6206896551724138,
  1.0149425287356322),
 ('Male',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  139,
  0.15741789354473387,
  0.6017316017316018,
  0.9839426006092673),
 ('Male',
  ('3_JIvol', 'Travel_Rarely', 'No'),
  207,
  0.23442808607021517,
  0.6160714285714286,
  1.007390873015873),
 ('Male',
  ('Bachelor', 'Travel_Rarely', 'No'),
  155,
  0.1755379388448471,
  0.62,
  1.0138148148148147),
 ('Male',
  ('MidLevel', 'Travel_Rarely', 'No'),
  144,
  0.16308040770101925,
  0.62882096069869,
  1.0282387190684135),
 ('Male',
  ('[11.0, 13.8)_%', 'Travel_Rarely', 'No'),
  158,
  0.17893544733861835,
  0.6583333333333333,
  1.076496913580247),
 ('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('Travel_Rarely',
  ('2.0_Time', '3_JIvol', 'No'),
  156,
  0.17667044167610418,
  0.6964285714285714,
  0.9489914021164021),
 ('Travel_Rarely',
  ('2.0_Time', 'Male', 'No'),
  179,
  0.20271800679501698,
  0.7366255144032922,
  1.0037659401513996),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance', 'No'),
  215,
  0.2434881087202718,
  0.7413793103448276,
  1.0102437207322266),
 ('Travel_Rarely',
  ('3_JIvol', 'Male', 'No'),
  207,
  0.23442808607021517,
  0.6946308724832215,
  0.946541759880686),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male', 'No'),
  221,
  0.25028312570781425,
  0.7542662116040956,
  1.0278041124173092)}

In [58]:
rules1 = apriori(baskets, supp=25, zmin=4, target='r', conf=70, 
                report='ascl') 
print('Number of rule:', len(rules1))
set(rules1)

Number of rule: 6

{('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264),
 ('Travel_Rarely',
  ('2.0_Time', 'Male', 'No'),
  179,
  0.20271800679501698,
  0.7366255144032922,
  1.0037659401513996),
 ('Travel_Rarely',
  ('3_JIvol', '3_WLBalance', 'No'),
  215,
  0.2434881087202718,
  0.7413793103448276,
  1.0102437207322266),
 ('Travel_Rarely',
  ('3_WLBalance', 'Male', 'No'),
  221,
  0.25028312570781425,
  0.7542662116040956,
  1.0278041124173092)}

In [59]:
rules2 = apriori(baskets, supp=25, zmin=4, target='r', conf=80, 
                report='ascl') 
print('Number of rule:', len(rules2))
set(rules2)

Number of rule: 3

{('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264)}

In [60]:
rules3 = apriori(baskets, supp=25, zmin=4, target='r', conf=90, 
                report='ascl') 
print('Number of rule:', len(rules3))
set(rules3)

Number of rule: 3

{('No',
  ('3_JIvol', '3_WLBalance', 'Travel_Rarely'),
  215,
  0.2434881087202718,
  0.9307359307359307,
  1.0234618017930597),
 ('No',
  ('3_JIvol', 'Male', 'Travel_Rarely'),
  207,
  0.23442808607021517,
  0.92,
  1.0116562889165628),
 ('No',
  ('3_WLBalance', 'Male', 'Travel_Rarely'),
  221,
  0.25028312570781425,
  0.9208333333333333,
  1.0125726442507264)}

In [61]:
print('Numeber of rules with support = 25 e zmin = 4')

print('Number of rules, confidance [60]:', len(rules))
print('Number of rules, confidance [70]:', len(rules1))
print('Number of rules, confidance [80]:', len(rules2))
print('Number of rules, confidance [90]:', len(rules3))

Numeber of rules with support = 25 e zmin = 4
Number of rules, confidance [60]: 30
Number of rules, confidance [70]: 6
Number of rules, confidance [80]: 3
Number of rules, confidance [90]: 3