# ASSOCIATION RULES
Express how product/services relate to each other, and tend to group together.

Library import

In [51]:
#vanno importate pandas e numpy e matplot per fare i grafici
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split  
from pandas import DataFrame

In [52]:
df = pd.read_csv(r'C:\Users\jigok\OneDrive\Desktop\UniPISA\1semestre1Anno\Data Mining\Progetto\Dataset AR\All_values_Train_HR_Employee_Attrition.csv')

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    883 non-null    float64
 1   Attrition              883 non-null    object
 2   BusinessTravel         883 non-null    object
 3   DistanceFromHome       883 non-null    int64
 4   Education              883 non-null    int64
 5   Gender                 883 non-null    object
 6   JobLevel               883 non-null    int64
 7   JobRole                883 non-null    object
 8   MonthlyIncome          883 non-null    float64
 9   NumCompaniesWorked     883 non-null    int64
 10  OverTime               883 non-null    object
 11  PercentSalaryHike      883 non-null    int64
 12  StockOptionLevel       883 non-null    int64
 13  TrainingTimesLastYear  883 non-null    float64
 14  YearsAtCompany         883 non-null    float64
 15  YearsInCurrentRole     883 non-null    int64
 16  MonthlyHours           883 non-null    float64
 17  TaxRate                883 non-null    float64
 18  OverallSatisfaction    883 non-null    float64
dtypes: float64(7), int64(7), object(5)
memory usage: 131.2+ KB

In [54]:
df.head(5) #fammi vedere le prime 10 righe

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,Gender,JobLevel,JobRole,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,MonthlyHours,TaxRate,OverallSatisfaction
0,52.0,No,Travel_Rarely,9,4,Male,3,Research Director,8446.0,9,No,17,0,2.0,8.0,7,156.613636,0.387172,2.6
1,36.0,No,Travel_Rarely,1,1,Male,5,Manager,4834.0,1,Yes,14,1,3.0,1.0,8,157.942308,0.411421,2.8
2,25.0,No,Travel_Frequently,16,3,Male,2,Sales Executive,4768.0,1,Yes,25,1,4.0,1.0,5,448.055556,0.704402,3.2
3,33.0,No,Travel_Rarely,5,4,Male,1,Research Scientist,2799.0,2,No,14,0,1.0,3.0,7,271.907692,0.841632,2.4
4,31.0,No,Travel_Rarely,9,2,Female,1,Laboratory Technician,6319.0,1,No,12,0,2.0,10.0,2,106.373333,0.207947,3.2

In [55]:
#discretizzo OverallSatisfaction
def labels(x):
    if  1.0 <= x <= 1.5:
        return(1)
    elif 1.6 <= x <= 2.5:
        return(2)
    elif 2.6 <= x <= 3.5:
        return(3)
    elif 3.6 <= x <= 4.5:
        return(4)
    else:
        return(4)

df['OverallSatisfaction'] = df['OverallSatisfaction'].apply(lambda x: labels(x))
#arrotondo le medie
df.head(5)

,Age,Attrition,BusinessTravel,DistanceFromHome,Education,Gender,JobLevel,JobRole,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,MonthlyHours,TaxRate,OverallSatisfaction
0,52.0,No,Travel_Rarely,9,4,Male,3,Research Director,8446.0,9,No,17,0,2.0,8.0,7,156.613636,0.387172,3
1,36.0,No,Travel_Rarely,1,1,Male,5,Manager,4834.0,1,Yes,14,1,3.0,1.0,8,157.942308,0.411421,3
2,25.0,No,Travel_Frequently,16,3,Male,2,Sales Executive,4768.0,1,Yes,25,1,4.0,1.0,5,448.055556,0.704402,3
3,33.0,No,Travel_Rarely,5,4,Male,1,Research Scientist,2799.0,2,No,14,0,1.0,3.0,7,271.907692,0.841632,2
4,31.0,No,Travel_Rarely,9,2,Female,1,Laboratory Technician,6319.0,1,No,12,0,2.0,10.0,2,106.373333,0.207947,3

In [56]:
df.describe()

,Age,DistanceFromHome,Education,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,MonthlyHours,TaxRate,OverallSatisfaction
count,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000,883.000000
mean,36.554926,9.201586,2.886750,1.919592,6932.335221,2.836920,15.207248,0.793884,2.665912,6.326161,3.919592,234.245826,0.463811,2.725934
std,8.266129,8.241818,1.008285,1.007506,5453.370217,2.484993,3.589332,0.865362,1.187828,4.523567,3.435392,130.196628,0.320030,0.523459
min,18.000000,1.000000,1.000000,1.000000,1009.000000,0.000000,11.000000,0.000000,0.000000,0.000000,0.000000,26.043478,0.000000,1.000000
25%,30.000000,2.000000,2.000000,1.000000,3072.000000,1.000000,12.000000,0.000000,2.000000,3.000000,2.000000,130.630208,0.129730,2.000000
50%,35.000000,7.000000,3.000000,2.000000,5079.000000,2.000000,14.000000,1.000000,2.000000,5.000000,3.000000,212.279070,0.528359,3.000000
75%,42.000000,14.000000,4.000000,2.000000,8840.500000,4.000000,18.000000,1.000000,3.000000,9.000000,7.000000,309.906250,0.762560,3.000000
max,60.000000,29.000000,5.000000,5.000000,26997.000000,9.000000,25.000000,3.000000,6.000000,20.000000,16.000000,590.976744,0.951396,4.000000

In [57]:
#numero bin con la distribuzione istogrammi variabili
#Apply binning to continuous features

df['AgeBin'] = pd.cut(df['Age'].astype(int), 6, right=False)
df['DistanceFromHomeBin'] = pd.cut(df['DistanceFromHome'].astype(int), 10, right=False)
df['PercentSalaryHikeBin'] = pd.cut(df['PercentSalaryHike'].astype(int), 5, right=False)
df['MonthlyIncomeBin'] = pd.cut(df['MonthlyIncome'].astype(int), 10, right=False)
df['MonthlyHoursBin'] = pd.cut(df['MonthlyHours'].astype(int), 10, right=False)



df.drop(['Age', 'MonthlyIncome', 'MonthlyHours','DistanceFromHome','PercentSalaryHike'], axis=1, inplace=True)

df.head()

,Attrition,BusinessTravel,Education,Gender,JobLevel,JobRole,NumCompaniesWorked,OverTime,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,TaxRate,OverallSatisfaction,AgeBin,DistanceFromHomeBin,PercentSalaryHikeBin,MonthlyIncomeBin,MonthlyHoursBin
0,No,Travel_Rarely,4,Male,3,Research Director,9,No,0,2.0,8.0,7,0.387172,3,"[46.0, 53.0)","[6.6, 9.4)","[16.6, 19.4)","[6206.6, 8805.4)","[138.8, 195.2)"
1,No,Travel_Rarely,1,Male,5,Manager,1,Yes,1,3.0,1.0,8,0.411421,3,"[32.0, 39.0)","[1.0, 3.8)","[13.8, 16.6)","[3607.8, 6206.6)","[138.8, 195.2)"
2,No,Travel_Frequently,3,Male,2,Sales Executive,1,Yes,1,4.0,1.0,5,0.704402,3,"[25.0, 32.0)","[15.0, 17.8)","[22.2, 25.014)","[3607.8, 6206.6)","[420.8, 477.2)"
3,No,Travel_Rarely,4,Male,1,Research Scientist,2,No,0,1.0,3.0,7,0.841632,2,"[32.0, 39.0)","[3.8, 6.6)","[13.8, 16.6)","[1009.0, 3607.8)","[251.6, 308.0)"
4,No,Travel_Rarely,2,Female,1,Laboratory Technician,1,No,0,2.0,10.0,2,0.207947,3,"[25.0, 32.0)","[6.6, 9.4)","[11.0, 13.8)","[6206.6, 8805.4)","[82.4, 138.8)"

Mapping

In [58]:
df['Education'] = df['Education'].map(
    {1: 'Below College', 2: 'College', 3:'Bachelor', 4:'Master', 5:'Doctor'}).astype(str)
df['OverallSatisfaction'] = df['OverallSatisfaction'].map(
    {1: 'Low', 2: 'Medium', 3:'High', 4:'Very High'}).astype(str)+'_Overall'
df['JobLevel'] = df['JobLevel'].map(
    {1: 'EntryLevel', 2: 'MidLevel', 3:'SeniorLevel', 4:'Manager', 5:'Director'}).astype(str)


df['AgeBin'] = df['AgeBin'].astype(str) + '_Age'
df['MonthlyIncomeBin'] = df['MonthlyIncomeBin'].astype(str) + '_Income'
df['MonthlyHoursBin'] = df['MonthlyHoursBin'].astype(str) + '_Hours'
df['DistanceFromHomeBin'] = df['DistanceFromHomeBin'].astype(str) + '_Distance'
df['YearsAtCompany'] = df['YearsAtCompany'].astype(str) + '_YearsAtCompany'
df['PercentSalaryHikeBin'] = df['PercentSalaryHikeBin'].astype(str) + '_%'

df['NumCompaniesWorked'] = df['NumCompaniesWorked'].astype(str) + '_companies'
df['StockOptionLevel'] = df['StockOptionLevel'].astype(str) + '_stockOption'
df['TrainingTimesLastYear'] = df['TrainingTimesLastYear'].astype(str) + '_Time'
df['YearsInCurrentRole'] = df['YearsInCurrentRole'].astype(str) + '_YearsInCurrentRole'
df['TaxRate'] = df['TaxRate'].astype(str) + '_TaxRate'
df['OverTime'] = df['OverTime'].astype(str) + '_OverTime'
df['Attrition'] = df['Attrition'].astype(str) + '_Attrition'


df.head(5)

,Attrition,BusinessTravel,Education,Gender,JobLevel,JobRole,NumCompaniesWorked,OverTime,StockOptionLevel,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,TaxRate,OverallSatisfaction,AgeBin,DistanceFromHomeBin,PercentSalaryHikeBin,MonthlyIncomeBin,MonthlyHoursBin
0,No_Attrition,Travel_Rarely,Master,Male,SeniorLevel,Research Director,9_companies,No_OverTime,0_stockOption,2.0_Time,8.0_YearsAtCompany,7_YearsInCurrentRole,0.3871716731969235_TaxRate,High_Overall,"[46.0, 53.0)_Age","[6.6, 9.4)_Distance","[16.6, 19.4)_%","[6206.6, 8805.4)_Income","[138.8, 195.2)_Hours"
1,No_Attrition,Travel_Rarely,Below College,Male,Director,Manager,1_companies,Yes_OverTime,1_stockOption,3.0_Time,1.0_YearsAtCompany,8_YearsInCurrentRole,0.4114209180567393_TaxRate,High_Overall,"[32.0, 39.0)_Age","[1.0, 3.8)_Distance","[13.8, 16.6)_%","[3607.8, 6206.6)_Income","[138.8, 195.2)_Hours"
2,No_Attrition,Travel_Frequently,Bachelor,Male,MidLevel,Sales Executive,1_companies,Yes_OverTime,1_stockOption,4.0_Time,1.0_YearsAtCompany,5_YearsInCurrentRole,0.7044017358958462_TaxRate,High_Overall,"[25.0, 32.0)_Age","[15.0, 17.8)_Distance","[22.2, 25.014)_%","[3607.8, 6206.6)_Income","[420.8, 477.2)_Hours"
3,No_Attrition,Travel_Rarely,Master,Male,EntryLevel,Research Scientist,2_companies,No_OverTime,0_stockOption,1.0_Time,3.0_YearsAtCompany,7_YearsInCurrentRole,0.8416317754894195_TaxRate,Medium_Overall,"[32.0, 39.0)_Age","[3.8, 6.6)_Distance","[13.8, 16.6)_%","[1009.0, 3607.8)_Income","[251.6, 308.0)_Hours"
4,No_Attrition,Travel_Rarely,College,Female,EntryLevel,Laboratory Technician,1_companies,No_OverTime,0_stockOption,2.0_Time,10.0_YearsAtCompany,2_YearsInCurrentRole,0.20794685384808226_TaxRate,High_Overall,"[25.0, 32.0)_Age","[6.6, 9.4)_Distance","[11.0, 13.8)_%","[6206.6, 8805.4)_Income","[82.4, 138.8)_Hours"

Conto le transazioni che contengono attrition(yes)e le totali

# Creo i baskets

In [59]:
baskets = df.values.tolist()

In [60]:
baskets[0]

['No_Attrition',
 'Travel_Rarely',
 'Master',
 'Male',
 'SeniorLevel',
 'Research Director',
 '9_companies',
 'No_OverTime',
 '0_stockOption',
 '2.0_Time',
 '8.0_YearsAtCompany',
 '7_YearsInCurrentRole',
 '0.3871716731969235_TaxRate',
 'High_Overall',
 '[46.0, 53.0)_Age',
 '[6.6, 9.4)_Distance',
 '[16.6, 19.4)_%',
 '[6206.6, 8805.4)_Income',
 '[138.8, 195.2)_Hours']

# Apriori Algorithm

In [61]:
from fim import apriori

In [62]:
help(apriori)

Help on built-in function apriori in module fim:

apriori(...)
    apriori (tracts, target='s', supp=10, zmin=1, zmax=None, report='a',
             eval='x', agg='x', thresh=10, prune=None, algo='b', mode='',
             border=None)
    Find frequent item sets with the Apriori algorithm.
    tracts  transaction database to mine (mandatory)
            The database must be an iterable of transactions;
            each transaction must be an iterable of items;
            each item must be a hashable object.
            If the database is a dictionary, the transactions are
            the keys, the values their (integer) multiplicities.
    target  type of frequent item sets to find     (default: s)
            s/a   sets/all   all     frequent item sets
            c     closed     closed  frequent item sets
            m     maximal    maximal frequent item sets
            g     gens       generators
            r     rules      association rules
    supp    minimum support of an item set         (default: 10)
            (positive: percentage, negative: absolute number)
    conf    minimum confidence of an assoc. rule   (default: 80%)
    zmin    minimum number of items per item set   (default: 1)
    zmax    maximum number of items per item set   (default: no limit)
    report  values to report with an item set      (default: a)
            a     absolute item set support (number of transactions)
            s     relative item set support as a fraction
            S     relative item set support as a percentage
            e     value of item set evaluation measure
            E     value of item set evaluation measure as a percentage
            (     combine values in a tuple (must be first character)
            [     combine values in a list  (must be first character)
            #     pattern spectrum as a dictionary  (no patterns)
            =     pattern spectrum as a list        (no patterns)
            |     pattern spectrum as three columns (no patterns)
            for target 'r' (association rules) also available:
            b     absolute body set  support (number of transactions)
            x     relative body set  support as a fraction
            X     relative body set  support as a percentage
            h     absolute head item support (number of transactions)
            y     relative head item support as a fraction
            Y     relative head item support as a percentage
            c     rule confidence as a fraction
            C     rule confidence as a percentage
            l     lift value of a rule (confidence/prior)
            L     lift value of a rule as a percentage
            Q     support of the empty set (total number of transactions)
    eval    measure for item set evaluation        (default: x)
            x     none       no measure / zero (default)
            b     ldratio    binary logarithm of support quotient       (+)
            c     conf       rule confidence                            (+)
            d     confdiff   absolute confidence difference to prior    (+)
            l     lift       lift value (confidence divided by prior)   (+)
            a     liftdiff   absolute difference of lift value to 1     (+)
            q     liftquot   difference of lift quotient to 1           (+)
            v     cvct       conviction (inverse lift negated head)     (+)
            e     cvctdiff   absolute difference of conviction to 1     (+)
            r     cvctquot   difference of conviction quotient to 1     (+)
            k     cprob      conditional probability ratio              (+)
            j     import     importance (binary log. of prob. ratio)    (+)
            z     cert       certainty factor (relative conf. change)   (+)
            n     chi2       normalized chi^2 measure                   (+)
            p     chi2pval   p-value f/ (unnormalized) chi^2 measure    (-)
            y     yates      normalized chi^2 with Yates' correction    (+)
            t     yatespval  p-value f/ Yates-corrected chi^2 measure   (-)
            i     info       information difference to prior            (+)
            g     infopval   p-value f/ G statistic/info. difference    (-)
            f     fetprob    Fisher's exact test (table probability)    (-)
            h     fetchi2    Fisher's exact test (chi^2 measure)        (-)
            m     fetinfo    Fisher's exact test (mutual information)   (-)
            s     fetsupp    Fisher's exact test (support)              (-)
            Measures marked with (+) must meet or exceed the threshold,
            measures marked with (-) must not exceed the threshold
            in order for the item set to be reported.
    agg     evaluation measure aggregation mode    (default: x)
            x     none       no aggregation (use first value)
            m     min        minimum of individual measure values
            n     max        maximum of individual measure values
            a     avg        average of individual measure values
    thresh  threshold for evaluation measure       (default: 10%)
    prune   min. size for evaluation filtering     (default: no pruning)
            = 0   backward filtering       (no subset check)
            < 0   weak   forward filtering (one subset  must qualify)
            > 0   strong forward filtering (all subsets must qualify)
    algo    algorithm variant to use               (default: a)
            b     basic      standard algorithm (only choice)
    mode    operation mode indicators/flags        (default: None)
            x     do not use perfect extension pruning
            t/T   do not organize transactions as a prefix tree
            y     a-posteriori pruning of infrequent item sets
            z     invalidate evaluation below expected support
            o     use original rule support definition (body & head)
    border  support border for filtering item sets (default: None)
            Must be a list or tuple of (absolute) minimum support values
            per item set size (by which the list/tuple is indexed).
    appear  dictionary mapping items to item appearance indicators,
            with the key None referring to the default item appearance.
            (If None does not occur as a key or no dictionary is given,
            the default item appearance indicator is 'both'.)
            This parameter is only used if the target type is rules.
            * item may not appear anywhere in a rule:
              '-', 'n', 'none', 'neither', 'ignore'
            * item may appear only in rule body/antecedent:
              'i', 'in', 'inp', 'input', 'b', 'body',
              'a', 'ante', 'antecedent'
            * item may appear only in rule head/consequent:
              'o', 'out',      'output', 'h', 'head',
              'c', 'cons', 'consequent'
            * item may appear anywhere in a rule:
              'io', 'i&o', 'inout', 'in&out', 'bh', 'b&h', 'both'
    returns if report is not in ['#','=','|']:
              if the target is association rules:
                a list of rules (i.e. tuples with two or more elements),
                each consisting of a head/consequent item, a tuple with
                a body/antecedent item set, and the values selected by
                the parameter 'report', which may be combined into a
                tuple or a list if report[0] is '(' or '[', respectively.
              if the target is a type of item sets:
                a list of patterns (i.e. tuples with one or more elements),
                each consisting of a tuple with a found frequent item set
                and the values selected by the parameter 'report', which
                may be combined into a tuple or list if report[0] is '('
                or '[', respectively
            if report in ['#','=','|']:
              a pattern spectrum as a dictionary mapping pattern sizes
              to the corresponding occurrence support ranges, as a list
              of triplets (size, min. support, max. support) or as three
              columns for sizes and minimum and maximum support values

# Description of the Value

We have decide to do some proves with different characterized value of support. This value are 2,10,20,30,40,50,60,70,80,90.
After that we have to do some proves with different type of target , a for frequent itemset, m for maximal itemset e c for closed itemset. 

For choosing the best combination we try to create the frequent itemset with different min value from the range 0-19.

# Support = 2%

 Frequent Itemsets with min value in a range 0 to 19

In [63]:
x = 0
for x in range (19):
    items = apriori(baskets, supp=2, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 39756
Number of itemsets for zimin 1 : 39755
Number of itemsets for zimin 2 : 39644
Number of itemsets for zimin 3 : 37725
Number of itemsets for zimin 4 : 29110
Number of itemsets for zimin 5 : 14538
Number of itemsets for zimin 6 : 3830
Number of itemsets for zimin 7 : 374
Number of itemsets for zimin 8 : 4
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

Maximal Itemset with min value  in a range 0 to 19

In [64]:
x = 0
for x in range (19):
    items1 = apriori(baskets, supp=2, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items1))

Number of itemsets for zimin 0 : 12377
Number of itemsets for zimin 1 : 12377
Number of itemsets for zimin 2 : 12376
Number of itemsets for zimin 3 : 12174
Number of itemsets for zimin 4 : 10550
Number of itemsets for zimin 5 : 6557
Number of itemsets for zimin 6 : 2404
Number of itemsets for zimin 7 : 346
Number of itemsets for zimin 8 : 4
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

Closed Itemset with min value in a range 0 to 19

In [65]:
x = 0
for x in range (19):
    items2 = apriori(baskets, supp=2, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items2))

Number of itemsets for zimin 0 : 38516
Number of itemsets for zimin 1 : 38515
Number of itemsets for zimin 2 : 38409
Number of itemsets for zimin 3 : 36529
Number of itemsets for zimin 4 : 28149
Number of itemsets for zimin 5 : 14089
Number of itemsets for zimin 6 : 3745
Number of itemsets for zimin 7 : 374
Number of itemsets for zimin 8 : 4
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

# Association Rule

Here we have a cycle for all the minimum number of rule, basys on the fact that we have 19 columns, with different value of  Confidance

In [66]:
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=2, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 122550
Number of rule with Confidance 60 % and zmin 1 : 122550
Number of rule with Confidance 60 % and zmin 2 : 122545
Number of rule with Confidance 60 % and zmin 3 : 122041
Number of rule with Confidance 60 % and zmin 4 : 113748
Number of rule with Confidance 60 % and zmin 5 : 80743
Number of rule with Confidance 60 % and zmin 6 : 33561
Number of rule with Confidance 60 % and zmin 7 : 6500
Number of rule with Confidance 60 % and zmin 8 : 375
Number of rule with Confidance 60 % and zmin 9 : 3
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 72985
Number of rule with Confidance 70 % and zmin 1 : 72985
Number of rule with Confidance 70 % and zmin 2 : 72982
Number of rule with Confidance 70 % and zmin 3 : 72665
Number of rule with Confidance 70 % and zmin 4 : 67560
Number of rule with Confidance 70 % and zmin 5 : 47404
Number of rule with Confidance 70 % and zmin 6 : 19057
Number of rule with Confidance 70 % and zmin 7 : 3397
Number of rule with Confidance 70 % and zmin 8 : 143
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 31663
Number of rule with Confidance 80 % and zmin 1 : 31663
Number of rule with Confidance 80 % and zmin 2 : 31662
Number of rule with Confidance 80 % and zmin 3 : 31550
Number of rule with Confidance 80 % and zmin 4 : 29458
Number of rule with Confidance 80 % and zmin 5 : 20760
Number of rule with Confidance 80 % and zmin 6 : 8177
Number of rule with Confidance 80 % and zmin 7 : 1334
Number of rule with Confidance 80 % and zmin 8 : 38
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 8736
Number of rule with Confidance 90 % and zmin 1 : 8736
Number of rule with Confidance 90 % and zmin 2 : 8736
Number of rule with Confidance 90 % and zmin 3 : 8719
Number of rule with Confidance 90 % and zmin 4 : 8234
Number of rule with Confidance 90 % and zmin 5 : 5912
Number of rule with Confidance 90 % and zmin 6 : 2291
Number of rule with Confidance 90 % and zmin 7 : 331
Number of rule with Confidance 90 % and zmin 8 : 4
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

In [67]:
rules = apriori(baskets, supp=2, zmin=3, target='r', conf=80, 
                report='ascl') 
print('Number of rule:', len(rules))

for r in rules:
    if r[0] == 'Yes_Attrition':
        print(r)

Number of rule: 31550
('Yes_Attrition', ('Laboratory Technician', 'Yes_OverTime', 'Bachelor', 'EntryLevel'), 15, 0.01698754246885617, 0.8333333333333334, 4.809368191721133)
('Yes_Attrition', ('Yes_OverTime', 'Medium_Overall', 'EntryLevel', 'Male'), 17, 0.01925254813137033, 0.8095238095238095, 4.671957671957672)
('Yes_Attrition', ('Yes_OverTime', 'Medium_Overall', 'EntryLevel', 'Travel_Rarely'), 17, 0.01925254813137033, 0.8095238095238095, 4.671957671957672)
('Yes_Attrition', ('Yes_OverTime', 'Medium_Overall', 'EntryLevel'), 24, 0.027180067950169876, 0.8275862068965517, 4.776200135226504)
('Yes_Attrition', ('Yes_OverTime', '1_companies', 'EntryLevel', '0_stockOption', 'Travel_Rarely'), 17, 0.01925254813137033, 0.85, 4.905555555555556)
('Yes_Attrition', ('Yes_OverTime', 'Bachelor', 'EntryLevel', '0_stockOption'), 17, 0.01925254813137033, 0.8095238095238095, 4.671957671957672)
('Yes_Attrition', ('Yes_OverTime', 'EntryLevel', '0_stockOption', '2.0_Time', 'Travel_Rarely'), 17, 0.01925254813137033, 0.8095238095238095, 4.671957671957672)
('Yes_Attrition', ('Yes_OverTime', 'EntryLevel', '0_stockOption', 'Male', 'Travel_Rarely'), 19, 0.021517553793884484, 0.8260869565217391, 4.767547598749645)
('Yes_Attrition', ('Yes_OverTime', 'EntryLevel', '0_stockOption', 'Travel_Rarely'), 28, 0.031710079275198186, 0.8, 4.616993464052287)

# Support =10%

In [68]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=10, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 1089
Number of itemsets for zimin 1 : 1088
Number of itemsets for zimin 2 : 1033
Number of itemsets for zimin 3 : 721
Number of itemsets for zimin 4 : 245
Number of itemsets for zimin 5 : 33
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [69]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=10, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 447
Number of itemsets for zimin 1 : 447
Number of itemsets for zimin 2 : 438
Number of itemsets for zimin 3 : 355
Number of itemsets for zimin 4 : 149
Number of itemsets for zimin 5 : 33
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [70]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=10, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 1089
Number of itemsets for zimin 1 : 1088
Number of itemsets for zimin 2 : 1033
Number of itemsets for zimin 3 : 721
Number of itemsets for zimin 4 : 245
Number of itemsets for zimin 5 : 33
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [71]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=10, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 3400
Number of rule with Confidance 60 % and zmin 1 : 3400
Number of rule with Confidance 60 % and zmin 2 : 3395
Number of rule with Confidance 60 % and zmin 3 : 3151
Number of rule with Confidance 60 % and zmin 4 : 1933
Number of rule with Confidance 60 % and zmin 5 : 456
Number of rule with Confidance 60 % and zmin 6 : 27
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 2053
Number of rule with Confidance 70 % and zmin 1 : 2053
Number of rule with Confidance 70 % and zmin 2 : 2050
Number of rule with Confidance 70 % and zmin 3 : 1898
Number of rule with Confidance 70 % and zmin 4 : 1154
Number of rule with Confidance 70 % and zmin 5 : 250
Number of rule with Confidance 70 % and zmin 6 : 9
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 581
Number of rule with Confidance 80 % and zmin 1 : 581
Number of rule with Confidance 80 % and zmin 2 : 580
Number of rule with Confidance 80 % and zmin 3 : 532
Number of rule with Confidance 80 % and zmin 4 : 317
Number of rule with Confidance 80 % and zmin 5 : 62
Number of rule with Confidance 80 % and zmin 6 : 1
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 108
Number of rule with Confidance 90 % and zmin 1 : 108
Number of rule with Confidance 90 % and zmin 2 : 108
Number of rule with Confidance 90 % and zmin 3 : 105
Number of rule with Confidance 90 % and zmin 4 : 74
Number of rule with Confidance 90 % and zmin 5 : 17
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

In [72]:
rules = apriori(baskets, supp=10, zmin=3, target='r', conf=50, 
                report='ascl') 
print('Number of rule:', len(rules))

for r in rules:
    if r[0] == 'Yes_Attrition':
        print(r)

Number of rule: 3968
('Yes_Attrition', ('Yes_OverTime', 'EntryLevel'), 56, 0.06342015855039637, 0.5833333333333334, 3.366557734204793)

# Support =17%

In [73]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=17, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 291
Number of itemsets for zimin 1 : 290
Number of itemsets for zimin 2 : 255
Number of itemsets for zimin 3 : 139
Number of itemsets for zimin 4 : 29
Number of itemsets for zimin 5 : 1
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [74]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=17, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 119
Number of itemsets for zimin 1 : 119
Number of itemsets for zimin 2 : 111
Number of itemsets for zimin 3 : 74
Number of itemsets for zimin 4 : 24
Number of itemsets for zimin 5 : 1
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [75]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=17, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 291
Number of itemsets for zimin 1 : 290
Number of itemsets for zimin 2 : 255
Number of itemsets for zimin 3 : 139
Number of itemsets for zimin 4 : 29
Number of itemsets for zimin 5 : 1
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [76]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=17, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 916
Number of rule with Confidance 60 % and zmin 1 : 916
Number of rule with Confidance 60 % and zmin 2 : 911
Number of rule with Confidance 60 % and zmin 3 : 754
Number of rule with Confidance 60 % and zmin 4 : 329
Number of rule with Confidance 60 % and zmin 5 : 44
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 549
Number of rule with Confidance 70 % and zmin 1 : 549
Number of rule with Confidance 70 % and zmin 2 : 546
Number of rule with Confidance 70 % and zmin 3 : 450
Number of rule with Confidance 70 % and zmin 4 : 187
Number of rule with Confidance 70 % and zmin 5 : 16
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 150
Number of rule with Confidance 80 % and zmin 1 : 150
Number of rule with Confidance 80 % and zmin 2 : 149
Number of rule with Confidance 80 % and zmin 3 : 122
Number of rule with Confidance 80 % and zmin 4 : 52
Number of rule with Confidance 80 % and zmin 5 : 2
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 29
Number of rule with Confidance 90 % and zmin 1 : 29
Number of rule with Confidance 90 % and zmin 2 : 29
Number of rule with Confidance 90 % and zmin 3 : 28
Number of rule with Confidance 90 % and zmin 4 : 16
Number of rule with Confidance 90 % and zmin 5 : 1
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support =40%

In [77]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=40, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 23
Number of itemsets for zimin 1 : 22
Number of itemsets for zimin 2 : 12
Number of itemsets for zimin 3 : 3
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [78]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=40, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 11
Number of itemsets for zimin 1 : 11
Number of itemsets for zimin 2 : 6
Number of itemsets for zimin 3 : 3
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [79]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=40, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 23
Number of itemsets for zimin 1 : 22
Number of itemsets for zimin 2 : 12
Number of itemsets for zimin 3 : 3
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [80]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=40, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 76
Number of rule with Confidance 60 % and zmin 1 : 76
Number of rule with Confidance 60 % and zmin 2 : 71
Number of rule with Confidance 60 % and zmin 3 : 28
Number of rule with Confidance 60 % and zmin 4 : 4
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 45
Number of rule with Confidance 70 % and zmin 1 : 45
Number of rule with Confidance 70 % and zmin 2 : 42
Number of rule with Confidance 70 % and zmin 3 : 17
Number of rule with Confidance 70 % and zmin 4 : 2
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 12
Number of rule with Confidance 80 % and zmin 1 : 12
Number of rule with Confidance 80 % and zmin 2 : 11
Number of rule with Confidance 80 % and zmin 3 : 5
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 1
Number of rule with Confidance 90 % and zmin 1 : 1
Number of rule with Confidance 90 % and zmin 2 : 1
Number of rule with Confidance 90 % and zmin 3 : 1
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support = 50%

In [81]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=50, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 11
Number of itemsets for zimin 1 : 10
Number of itemsets for zimin 2 : 5
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [82]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=50, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 5
Number of itemsets for zimin 1 : 5
Number of itemsets for zimin 2 : 5
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [83]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=50, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 11
Number of itemsets for zimin 1 : 10
Number of itemsets for zimin 2 : 5
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [84]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=50, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 38
Number of rule with Confidance 60 % and zmin 1 : 38
Number of rule with Confidance 60 % and zmin 2 : 33
Number of rule with Confidance 60 % and zmin 3 : 14
Number of rule with Confidance 60 % and zmin 4 : 0
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 23
Number of rule with Confidance 70 % and zmin 1 : 23
Number of rule with Confidance 70 % and zmin 2 : 20
Number of rule with Confidance 70 % and zmin 3 : 8
Number of rule with Confidance 70 % and zmin 4 : 0
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 6
Number of rule with Confidance 80 % and zmin 1 : 6
Number of rule with Confidance 80 % and zmin 2 : 5
Number of rule with Confidance 80 % and zmin 3 : 1
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 0
Number of rule with Confidance 90 % and zmin 1 : 0
Number of rule with Confidance 90 % and zmin 2 : 0
Number of rule with Confidance 90 % and zmin 3 : 0
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support =60%

In [85]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=60, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 8
Number of itemsets for zimin 1 : 7
Number of itemsets for zimin 2 : 2
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [86]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=60, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 4
Number of itemsets for zimin 1 : 4
Number of itemsets for zimin 2 : 2
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [87]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=60, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 8
Number of itemsets for zimin 1 : 7
Number of itemsets for zimin 2 : 2
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [88]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=60, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 30
Number of rule with Confidance 60 % and zmin 1 : 30
Number of rule with Confidance 60 % and zmin 2 : 25
Number of rule with Confidance 60 % and zmin 3 : 6
Number of rule with Confidance 60 % and zmin 4 : 0
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 18
Number of rule with Confidance 70 % and zmin 1 : 18
Number of rule with Confidance 70 % and zmin 2 : 15
Number of rule with Confidance 70 % and zmin 3 : 3
Number of rule with Confidance 70 % and zmin 4 : 0
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 5
Number of rule with Confidance 80 % and zmin 1 : 5
Number of rule with Confidance 80 % and zmin 2 : 4
Number of rule with Confidance 80 % and zmin 3 : 0
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 0
Number of rule with Confidance 90 % and zmin 1 : 0
Number of rule with Confidance 90 % and zmin 2 : 0
Number of rule with Confidance 90 % and zmin 3 : 0
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support =70%

In [89]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=70, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 4
Number of itemsets for zimin 1 : 3
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [90]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=70, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 3
Number of itemsets for zimin 1 : 3
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [91]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=70, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 4
Number of itemsets for zimin 1 : 3
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [92]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=70, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 17
Number of rule with Confidance 60 % and zmin 1 : 17
Number of rule with Confidance 60 % and zmin 2 : 12
Number of rule with Confidance 60 % and zmin 3 : 0
Number of rule with Confidance 60 % and zmin 4 : 0
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 9
Number of rule with Confidance 70 % and zmin 1 : 9
Number of rule with Confidance 70 % and zmin 2 : 6
Number of rule with Confidance 70 % and zmin 3 : 0
Number of rule with Confidance 70 % and zmin 4 : 0
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 3
Number of rule with Confidance 80 % and zmin 1 : 3
Number of rule with Confidance 80 % and zmin 2 : 2
Number of rule with Confidance 80 % and zmin 3 : 0
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 0
Number of rule with Confidance 90 % and zmin 1 : 0
Number of rule with Confidance 90 % and zmin 2 : 0
Number of rule with Confidance 90 % and zmin 3 : 0
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support =80%

In [93]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=80, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 2
Number of itemsets for zimin 1 : 1
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [94]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=80, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 1
Number of itemsets for zimin 1 : 1
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [95]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=80, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 2
Number of itemsets for zimin 1 : 1
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [96]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=80, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 9
Number of rule with Confidance 60 % and zmin 1 : 9
Number of rule with Confidance 60 % and zmin 2 : 4
Number of rule with Confidance 60 % and zmin 3 : 0
Number of rule with Confidance 60 % and zmin 4 : 0
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 5
Number of rule with Confidance 70 % and zmin 1 : 5
Number of rule with Confidance 70 % and zmin 2 : 2
Number of rule with Confidance 70 % and zmin 3 : 0
Number of rule with Confidance 70 % and zmin 4 : 0
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 1
Number of rule with Confidance 80 % and zmin 1 : 1
Number of rule with Confidance 80 % and zmin 2 : 0
Number of rule with Confidance 80 % and zmin 3 : 0
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 0
Number of rule with Confidance 90 % and zmin 1 : 0
Number of rule with Confidance 90 % and zmin 2 : 0
Number of rule with Confidance 90 % and zmin 3 : 0
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0

# Support =90%

In [97]:
#Frequent
x = 0
for x in range (19):
    items = apriori(baskets, supp=90, report ='s', target='a',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 0
Number of itemsets for zimin 1 : 0
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [98]:
#Maximal
x = 0
for x in range (19):
    items = apriori(baskets, supp=90, report ='s', target='m',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 0
Number of itemsets for zimin 1 : 0
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [99]:
#Closed
x = 0
for x in range (19):
    items = apriori(baskets, supp=90, report ='s', target='c',zmin = x)
    print('Number of itemsets for zimin',x, ':' , len(items))

Number of itemsets for zimin 0 : 0
Number of itemsets for zimin 1 : 0
Number of itemsets for zimin 2 : 0
Number of itemsets for zimin 3 : 0
Number of itemsets for zimin 4 : 0
Number of itemsets for zimin 5 : 0
Number of itemsets for zimin 6 : 0
Number of itemsets for zimin 7 : 0
Number of itemsets for zimin 8 : 0
Number of itemsets for zimin 9 : 0
Number of itemsets for zimin 10 : 0
Number of itemsets for zimin 11 : 0
Number of itemsets for zimin 12 : 0
Number of itemsets for zimin 13 : 0
Number of itemsets for zimin 14 : 0
Number of itemsets for zimin 15 : 0
Number of itemsets for zimin 16 : 0
Number of itemsets for zimin 17 : 0
Number of itemsets for zimin 18 : 0

In [100]:
#Association Rule
y = range(19)
z = range(60,100,10)

for n in z:
    for m in y:
        rules = apriori(baskets, supp=90, zmin=m, target='r', conf=n, report='ascl')
        print('Number of rule with Confidance',n,'% and zmin',m,':', len(rules))

Number of rule with Confidance 60 % and zmin 0 : 5
Number of rule with Confidance 60 % and zmin 1 : 5
Number of rule with Confidance 60 % and zmin 2 : 0
Number of rule with Confidance 60 % and zmin 3 : 0
Number of rule with Confidance 60 % and zmin 4 : 0
Number of rule with Confidance 60 % and zmin 5 : 0
Number of rule with Confidance 60 % and zmin 6 : 0
Number of rule with Confidance 60 % and zmin 7 : 0
Number of rule with Confidance 60 % and zmin 8 : 0
Number of rule with Confidance 60 % and zmin 9 : 0
Number of rule with Confidance 60 % and zmin 10 : 0
Number of rule with Confidance 60 % and zmin 11 : 0
Number of rule with Confidance 60 % and zmin 12 : 0
Number of rule with Confidance 60 % and zmin 13 : 0
Number of rule with Confidance 60 % and zmin 14 : 0
Number of rule with Confidance 60 % and zmin 15 : 0
Number of rule with Confidance 60 % and zmin 16 : 0
Number of rule with Confidance 60 % and zmin 17 : 0
Number of rule with Confidance 60 % and zmin 18 : 0
Number of rule with Confidance 70 % and zmin 0 : 3
Number of rule with Confidance 70 % and zmin 1 : 3
Number of rule with Confidance 70 % and zmin 2 : 0
Number of rule with Confidance 70 % and zmin 3 : 0
Number of rule with Confidance 70 % and zmin 4 : 0
Number of rule with Confidance 70 % and zmin 5 : 0
Number of rule with Confidance 70 % and zmin 6 : 0
Number of rule with Confidance 70 % and zmin 7 : 0
Number of rule with Confidance 70 % and zmin 8 : 0
Number of rule with Confidance 70 % and zmin 9 : 0
Number of rule with Confidance 70 % and zmin 10 : 0
Number of rule with Confidance 70 % and zmin 11 : 0
Number of rule with Confidance 70 % and zmin 12 : 0
Number of rule with Confidance 70 % and zmin 13 : 0
Number of rule with Confidance 70 % and zmin 14 : 0
Number of rule with Confidance 70 % and zmin 15 : 0
Number of rule with Confidance 70 % and zmin 16 : 0
Number of rule with Confidance 70 % and zmin 17 : 0
Number of rule with Confidance 70 % and zmin 18 : 0
Number of rule with Confidance 80 % and zmin 0 : 1
Number of rule with Confidance 80 % and zmin 1 : 1
Number of rule with Confidance 80 % and zmin 2 : 0
Number of rule with Confidance 80 % and zmin 3 : 0
Number of rule with Confidance 80 % and zmin 4 : 0
Number of rule with Confidance 80 % and zmin 5 : 0
Number of rule with Confidance 80 % and zmin 6 : 0
Number of rule with Confidance 80 % and zmin 7 : 0
Number of rule with Confidance 80 % and zmin 8 : 0
Number of rule with Confidance 80 % and zmin 9 : 0
Number of rule with Confidance 80 % and zmin 10 : 0
Number of rule with Confidance 80 % and zmin 11 : 0
Number of rule with Confidance 80 % and zmin 12 : 0
Number of rule with Confidance 80 % and zmin 13 : 0
Number of rule with Confidance 80 % and zmin 14 : 0
Number of rule with Confidance 80 % and zmin 15 : 0
Number of rule with Confidance 80 % and zmin 16 : 0
Number of rule with Confidance 80 % and zmin 17 : 0
Number of rule with Confidance 80 % and zmin 18 : 0
Number of rule with Confidance 90 % and zmin 0 : 0
Number of rule with Confidance 90 % and zmin 1 : 0
Number of rule with Confidance 90 % and zmin 2 : 0
Number of rule with Confidance 90 % and zmin 3 : 0
Number of rule with Confidance 90 % and zmin 4 : 0
Number of rule with Confidance 90 % and zmin 5 : 0
Number of rule with Confidance 90 % and zmin 6 : 0
Number of rule with Confidance 90 % and zmin 7 : 0
Number of rule with Confidance 90 % and zmin 8 : 0
Number of rule with Confidance 90 % and zmin 9 : 0
Number of rule with Confidance 90 % and zmin 10 : 0
Number of rule with Confidance 90 % and zmin 11 : 0
Number of rule with Confidance 90 % and zmin 12 : 0
Number of rule with Confidance 90 % and zmin 13 : 0
Number of rule with Confidance 90 % and zmin 14 : 0
Number of rule with Confidance 90 % and zmin 15 : 0
Number of rule with Confidance 90 % and zmin 16 : 0
Number of rule with Confidance 90 % and zmin 17 : 0
Number of rule with Confidance 90 % and zmin 18 : 0